{{- $publicKey := "" -}}
{{- $privateKey := "" -}}
{{- if (include "testValuesPath" (list .Values "security" "gpg" "config" "publicKey")) | eq "true" -}}
  {{- if ne .Values.security.gpg.config.publicKey "" -}}
    {{- $publicKey = .Values.security.gpg.config.publicKey -}}
  {{- end -}}
{{- end -}}
{{- if (include "testValuesPath" (list .Values "security" "gpg" "config" "privateKey")) | eq "true" -}}
  {{- if ne .Values.security.gpg.config.privateKey "" -}}
    {{- $privateKey = .Values.security.gpg.config.privateKey -}}
  {{- end -}}
{{- end -}}
{{- if and (ne $publicKey "") (ne $privateKey "") -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-public-key" (include "gpg.fullname" .) }}
  labels:
    {{- include "gpg.labels" . | nindent 4 }}
data:
  public: {{ $publicKey | quote }}
{{- end }}
