{{- $publicKey := "" -}}
{{- $privateKey := "" -}}
{{- $passphrase := "" -}}
{{- if (include "testValuesPath" (list .Values "security" "gpg" "config" "publicKey")) | eq "true" -}}
  {{- if ne .Values.security.gpg.config.publicKey "" -}}
    {{- $publicKey = .Values.security.gpg.config.publicKey -}}
  {{- end -}}
{{- end -}}
{{- if (include "testValuesPath" (list .Values "security" "gpg" "config" "privateKey")) | eq "true" -}}
  {{- if ne .Values.security.gpg.config.privateKey "" -}}
    {{- $privateKey = .Values.security.gpg.config.privateKey -}}
  {{- end -}}
{{- end -}}
{{- if (include "testValuesPath" (list .Values "security" "gpg" "config" "passphrase")) | eq "true" -}}
  {{- if ne .Values.security.gpg.config.passphrase "" -}}
    {{- $passphrase = .Values.security.gpg.config.passphrase -}}
  {{- end -}}
{{- end -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-passphrase" (include "gpg.fullname" .) }}
  labels:
    {{- include "gpg.labels" . | nindent 4 }}
stringData:
  passphrase: {{ $passphrase | quote }}
