{{- if include "gpg.shouldGenerateKeys" . }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "gpg.fullname" . }}
  labels:
    ram-base-job: "true"
    {{- with (index .Values "gpg").labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    argocd.argoproj.io/sync-options: Skip
spec:
  template:
    metadata:
      {{- with .Values.security.gpg.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
      {{- include "gpg.labels" . | nindent 8 }}
      {{- with .Values.security.gpg.podLabels }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.images.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "gpg.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.security.gpg.podSecurityContext | nindent 8 }}
      initContainers:
        - name: check-secrets
          command:
            - "/bin/sh"
            - "-c"
            - "sh /scripts/check_secrets_exist.sh"
          image: "{{- include "images.kubectl" . -}}"
          imagePullPolicy: {{ .Values.images.kubectl.pullPolicy }}
          securityContext:
            {{- toYaml .Values.security.gpg.securityContext | nindent 12 }}
          resources:
            {{- toYaml .Values.security.gpg.resources | nindent 12 }}
          volumeMounts:
            - name: configmap-scripts
              mountPath: /scripts
            - name: shared-state
              mountPath: /shared
      containers:
        - name: gpg-creation
          command:
            - "/bin/sh"
            - "-c"
            - "sh /scripts/generate_gpg_keys.sh"
          image: "{{- include "images.gpg" . -}}"
          imagePullPolicy: {{ .Values.images.gpg.pullPolicy }}
          securityContext:
            {{- toYaml .Values.security.gpg.securityContext | nindent 12 }}
          resources:
            {{- toYaml .Values.security.gpg.resources | nindent 12 }}
          env:
            - name: KEY_NAME
              valueFrom:
                configMapKeyRef:
                  key: name
                  name: {{ include "gpg.fullname" . }}-settings
            - name: KEY_EMAIL
              valueFrom:
                configMapKeyRef:
                  key: email
                  name: {{ include "gpg.fullname" . }}-settings
            - name: KEY_COMMENT
              valueFrom:
                configMapKeyRef:
                  key: comment
                  name: {{ include "gpg.fullname" . }}-settings
            - name: KEY_LENGTH
              valueFrom:
                configMapKeyRef:
                  key: length
                  name: {{ include "gpg.fullname" . }}-settings
            - name: KEY_EXPIRE
              valueFrom:
                configMapKeyRef:
                  key: expire
                  name: {{ include "gpg.fullname" . }}-settings
            - name: KEY_PASSPHRASE
              valueFrom:
                secretKeyRef:
                  key: passphrase
                  name: {{ printf "%s-passphrase" (include "gpg.fullname" .) }}
          volumeMounts:
            - name: gpg-volume
              mountPath: /config/gpg
            - name: tmp-gpg-volume
              mountPath: /.gnupg
            - name: workdir
              mountPath: /workdir
            - name: configmap-scripts
              mountPath: /scripts
            - name: shared-state
              mountPath: /shared
        - name: apply-secrets
          command:
            - "/bin/sh"
            - "-c"
            - "sh /scripts/apply_secrets.sh"
          image: "{{- include "images.kubectl" . -}}"
          imagePullPolicy: {{ .Values.images.kubectl.pullPolicy }}
          securityContext:
            {{- toYaml .Values.security.gpg.securityContext | nindent 12 }}
          resources:
            {{- toYaml .Values.security.gpg.resources | nindent 12 }}
          volumeMounts:
            - name: gpg-volume
              mountPath: /config/gpg
            - name: configmap-scripts
              mountPath: /scripts
            - name: shared-state
              mountPath: /shared
      restartPolicy: OnFailure
      {{- with .Values.security.gpg.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.security.gpg.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.security.gpg.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: gpg-volume
          emptyDir:
            sizeLimit: 5Mi
        - name: tmp-gpg-volume
          emptyDir:
            sizeLimit: 5Mi
        - name: workdir
          emptyDir:
            sizeLimit: 128Mi
        - name: shared-state
          emptyDir:
            sizeLimit: 1Mi
        - name: configmap-scripts
          configMap:
            name: {{ include "gpg.fullname" . }}-scripts
            defaultMode: 0777
  backoffLimit: 1000
{{- end }}
