{{- if include "gpg.shouldGenerateKeys" . }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "gpg.fullname" . }}-settings
  labels:
    {{- include "gpg.labels" . | nindent 4 }}
data:
  name: {{ .Values.security.gpg.config.key.name | quote  }}
  email: {{ .Values.security.gpg.config.key.email | quote  }}
  comment: {{ .Values.security.gpg.config.key.comment | quote  }}
  length: {{ .Values.security.gpg.config.key.length | quote  }}
  expire: {{ .Values.security.gpg.config.key.expire | quote  }}
{{- end }}
