apiVersion: v2
name: keycloak
description: A Helm chart for Keycloak Identity and Access Management with OAuth2/OIDC support
type: application
version: 1.1.0
appVersion: "1.16.0"

# Chart metadata and repository information
home: https://www.keycloak.org/
sources:
  - https://github.com/keycloak/keycloak
  - https://github.com/sas-institute-rnd-internal/tmp-viya-iot-ram-helm
  - https://quay.io/repository/keycloak/keycloak
icon: https://www.sas.com/content/dam/SAS/sasbrand/Images/Logos/sas-logo-midnight.png

# Chart categorization and discovery
keywords:
  - keycloak
  - identity
  - access-management
  - oauth2
  - oidc
  - authentication
  - authorization
  - sso
  - single-sign-on
  - iam
  - security
  - federation
  - saml
  - jwt
  - kubernetes
  - sas

# Maintainer information
maintainers:
  - name: SAS Institute
    email: support@sas.com
    url: https://www.sas.com
  - name: Keycloak Team
    email: keycloak-dev@lists.jboss.org
    url: https://www.keycloak.org/

# Chart dependencies
dependencies:
  - name: mail
    version: "v4.4.0"
    # repository: "https://bokysan.github.io/docker-postfix/"
    condition: mail.enabled
    tags:
      - email
      - notifications

# Enhanced Artifact Hub annotations
annotations:
  # Licensing and legal information
  artifacthub.io/license: "Apache-2.0"
  artifacthub.io/operator: "false"
  artifacthub.io/prerelease: "false"
  
  # Chart documentation and links
  artifacthub.io/links: |
    - name: Keycloak Documentation
      url: https://www.keycloak.org/documentation
    - name: Keycloak Server Administration Guide
      url: https://www.keycloak.org/docs/latest/server_admin/
    - name: OAuth2/OIDC Configuration
      url: https://www.keycloak.org/docs/latest/securing_apps/
    - name: Source Repository
      url: https://github.com/keycloak/keycloak
  
  # Container images used by this chart
  artifacthub.io/images: |
    - name: keycloak
      image: quay.io/keycloak/keycloak:22.0.5
      whitelisted: true
    - name: keycloak-sas
      image: cr.sas.com/keycloak/keycloak:22.0.5
      whitelisted: true
    - name: postgres
      image: postgres:15
      whitelisted: true
    - name: sas-postgres
      image: cr.sas.com/postgresql/postgresql:15
      whitelisted: true
    - name: sas-keycloak-theme
      image: cr.sas.com/sas-iot-keycloak-theme:latest
      whitelisted: true
  
  # Deployment requirements and dependencies
  artifacthub.io/dependencies: |
    - name: postgresql
      version: ">=12.0.0"
      repository: https://charts.bitnami.com/bitnami
    - name: ingress-nginx
      version: ">=4.0.0"
      repository: https://kubernetes.github.io/ingress-nginx
      condition: ingress.enabled
    - name: mail
      version: "v4.4.0"
      repository: https://bokysan.github.io/docker-postfix/
      condition: mail.enabled
  
  # Resource allocation recommendations
  resources.cpu.min: "500m"
  resources.cpu.max: "2"
  resources.memory.min: "1Gi"
  resources.memory.max: "4Gi"
  
  # Database and storage requirements
  database.required: "true"
  database.type: "postgresql"
  database.version.min: "12.0"
  database.version.recommended: "15.0"
  storage.required: "true"
  storage.size.min: "1Gi"
  storage.size.recommended: "10Gi"
  
  # Security and authentication requirements
  security.oauth2.supported: "true"
  security.oidc.supported: "true"
  security.saml.supported: "true"
  security.ldap.supported: "true"
  security.social.supported: "true"
  authentication.mfa.supported: "true"
  authentication.federation.supported: "true"
  
  # Performance and scaling
  scaling.horizontal.supported: "true"
  scaling.replicas.min: "1"
  scaling.replicas.max: "10"
  scaling.replicas.recommended: "2"
  
  # Network and connectivity
  network.ingress.required: "true"
  network.tls.supported: "true"
  network.tls.recommended: "true"
  
  # Compatibility and version information
  kubernetes.version.min: "1.20.0"
  kubernetes.version.max: "1.30.0"
  helm.version.min: "3.8.0"
  
  # Chart category and classification
  category: "Security"
  subcategory: "Identity and Access Management"
  use-case: "Authentication and Authorization"
