apiVersion: v2
name: sas-retrieval-agent-manager-api
description: A Helm chart for SAS Retrieval Agent Manager API - Backend service with AI/ML capabilities for document retrieval and vectorization
type: application
version: 1.1.0
appVersion: "1.16.0"

# Chart metadata and repository information
home: https://www.sas.com/
sources:
  - https://github.com/sas-institute-rnd-internal/tmp-viya-iot-ram-helm
  - https://cr.sas.com/viya-4-x64_oci_linux_2-docker/sas-retrieval-agent-manager
icon: https://www.sas.com/content/dam/SAS/sasbrand/Images/Logos/sas-logo-midnight.png

# Chart categorization and discovery
keywords:
  - sas
  - retrieval-agent-manager
  - api
  - backend
  - artificial-intelligence
  - machine-learning
  - document-retrieval
  - vectorization
  - nlp
  - embeddings
  - vector-search
  - rag
  - retrieval-augmented-generation
  - query-hub
  - microservices
  - kubernetes
  - enterprise-ai

# Maintainer information
maintainers:
  - name: SAS Institute
    email: support@sas.com
    url: https://www.sas.com
  - name: SAS IoT Team
    email: iot-support@sas.com
    url: https://www.sas.com/en_us/software/iot.html

# Enhanced Artifact Hub annotations
annotations:
  # Licensing and legal information
  artifacthub.io/license: "SAS Proprietary"
  artifacthub.io/operator: "false"
  artifacthub.io/prerelease: "false"
  
  # Chart documentation and links
  artifacthub.io/links: |
    - name: SAS Viya Platform
      url: https://www.sas.com/en_us/software/viya.html
    - name: SAS AI and Machine Learning
      url: https://www.sas.com/en_us/software/artificial-intelligence.html
    - name: SAS IoT Solutions
      url: https://www.sas.com/en_us/software/iot.html
    - name: SAS Container Registry
      url: https://cr.sas.com/
  
  # Container images used by this chart
  artifacthub.io/images: |
    - name: sas-retrieval-agent-manager
      image: cr.sas.com/viya-4-x64_oci_linux_2-docker/sas-retrieval-agent-manager:latest
      whitelisted: true
  
  # Deployment requirements and dependencies
  artifacthub.io/dependencies: |
    - name: postgresql
      version: ">=15.0.0"
      repository: https://charts.bitnami.com/bitnami
    - name: keycloak
      version: ">=1.0.0"
      repository: local
    - name: ingress-nginx
      version: ">=4.0.0"
      repository: https://kubernetes.github.io/ingress-nginx
      condition: ingress.enabled
  
  # Resource allocation recommendations for AI/ML workloads
  resources.cpu.min: "1"
  resources.cpu.max: "8"
  resources.memory.min: "2Gi"
  resources.memory.max: "16Gi"
  
  # AI/ML specific requirements
  ai.gpu.supported: "true"
  ai.gpu.required: "false"
  ai.models.embeddings: "true"
  ai.models.llm: "true"
  ai.frameworks.pytorch: "true"
  ai.frameworks.tensorflow: "true"
  ai.frameworks.onnx: "true"
  
  # Vector database and search capabilities
  vectordb.supported: "true"
  vectordb.types: "weaviate,pinecone,chroma"
  search.semantic: "true"
  search.hybrid: "true"
  search.similarity: "cosine,euclidean,dot-product"
  
  # Document processing capabilities
  document.formats: "pdf,docx,txt,html,md"
  document.ocr: "true"
  document.chunking: "true"
  document.metadata: "true"
  
  # Security and enterprise features
  security.oauth2.supported: "true"
  security.rbac.supported: "true"
  security.encryption.at-rest: "true"
  security.encryption.in-transit: "true"
  enterprise.sso.supported: "true"
  enterprise.audit.supported: "true"
  
  # Performance and scaling for AI workloads
  scaling.horizontal.supported: "true"
  scaling.replicas.min: "1"
  scaling.replicas.max: "10"
  scaling.replicas.recommended: "2"
  scaling.auto.cpu-based: "true"
  scaling.auto.memory-based: "true"
  
  # API and integration capabilities
  api.rest.supported: "true"
  api.openapi.supported: "true"
  api.versioning.supported: "true"
  integration.webhook.supported: "true"
  integration.streaming.supported: "true"
  
  # Monitoring and observability for AI services
  monitoring.health-checks.supported: "true"
  monitoring.metrics.prometheus: "true"
  monitoring.logging.structured: "true"
  monitoring.tracing.distributed: "true"
  observability.model-performance: "true"
  
  # Storage and persistence
  storage.vector-embeddings: "true"
  storage.model-artifacts: "true"
  storage.document-cache: "true"
  persistence.required: "true"
  persistence.size.min: "10Gi"
  persistence.size.recommended: "100Gi"
  
  # Compatibility and version information
  kubernetes.version.min: "1.22.0"
  kubernetes.version.max: "1.30.0"
  helm.version.min: "3.10.0"
  
  # Chart category and classification
  category: "AI/ML"
  subcategory: "Document Retrieval"
  use-case: "Retrieval Augmented Generation"