# Default values for sas-retrieval-agent-manager-api.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# -- Number of replicas to run. Chart is not designed to scale horizontally, use at your own risk
replicaCount: 1

# -- Container image configuration for SAS Retrieval Agent Manager API
image:
  repo:
    # -- Container registry base URL
    base: cr.sas.com
    # -- Container image path/name
    path: cdp-release-x64_oci_linux_2-docker-latest/sas-retrieval-agent-manager
  # -- Container image tag
  tag: 1.1.20-20250829.1756485879782
  # -- Image pull policy
  pullPolicy: IfNotPresent

# -- Array of imagePullSecrets in the namespace for pulling images from private registries
imagePullSecrets:
  - name: cr-sas-secret

# -- String to partially override the fullname template with a string (will prepend the release name)
nameOverride: 'api'

# -- String to fully override the fullname template with a string
fullnameOverride: "sas-retrieval-agent-manager-api"

# -- Service account configuration
serviceAccount:
  # -- Annotations to add to the service account
  annotations: {}
  # -- Automatically mount a ServiceAccount's API credentials
  automount: true
  # -- Specifies whether a service account should be created
  create: true
  # -- The name of the service account to use. If not set and create is true, a name is generated using the fullname template
  name: ''

# -- Annotations to add to the pods
podAnnotations: {}

# -- Labels to add to the pods
podLabels:
  sas.com/deployment: "sas-retrieval-agent-manager"
  workload.sas.com/class: "ram"

# -- The security context for the pods
podSecurityContext:
  # -- Group ID for file system ownership
  fsGroup: 1001
  # -- Group ID to run the entrypoint of the container process
  runAsGroup: 1001
  # -- Indicates that the container must be run as a non-root user
  runAsNonRoot: true
  # -- User ID to run the entrypoint of the container process
  runAsUser: 1001
  # -- Seccomp profile for the pod
  seccompProfile:
    type: RuntimeDefault

# -- The security context for the application container
securityContext:
  # -- Seccomp profile for the container
  seccompProfile:
    type: RuntimeDefault
  # -- Whether a process can gain more privileges than its parent process
  allowPrivilegeEscalation: false
  # -- Linux capabilities to add/drop for the container
  capabilities:
    add: []
    drop:
      - ALL
  # -- Whether the container has a read-only root filesystem
  readOnlyRootFilesystem: true
  # -- Whether the container must be run as a non-root user
  runAsNonRoot: true
  # -- User ID to run the entrypoint of the container process
  runAsUser: 1001
  # -- Group ID to run the entrypoint of the container process
  runAsGroup: 1001

# -- Kubernetes Service configuration
service:
  # -- Kubernetes Service port
  port: 80
  # -- Kubernetes Service type
  type: ClusterIP

# -- Ingress configuration for external access
ingress:
  # -- Use global ingress configuration instead of local hosts configuration
  useGlobal: false
  # -- Enable ingress for external access
  enabled: true
  # -- Class name of the Ingress
  className: nginx
  # -- Annotations for the Ingress
  annotations:
    # -- Disallow HTTP traffic, force HTTPS only
    kubernetes.io/ingress.allow-http: 'false'
    # -- Enable TLS certificate management via cert-manager
    kubernetes.io/tls-acme: 'true'
    # -- Headers to pass from auth response to backend
    nginx.ingress.kubernetes.io/auth-response-headers: Authorization,X-Auth-Request-Access-Token
    # -- OAuth2 authentication sign-in URL
    nginx.ingress.kubernetes.io/auth-signin: https://$host/SASRetrievalAgentManager/oauth2/start?rd=$escaped_request_uri
    # -- OAuth2 authentication validation URL
    nginx.ingress.kubernetes.io/auth-url: https://$host/SASRetrievalAgentManager/oauth2/auth
    # -- Maximum allowed size of client request body
    nginx.ingress.kubernetes.io/proxy-body-size: 500m
    # -- Size of buffer used for reading the first part of response
    nginx.ingress.kubernetes.io/proxy-buffer-size: 16k
    # -- Force SSL redirect
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
  # -- Hosts configuration (used when useGlobal is false)
  hosts:
  - host: chart-example.local
    paths:
    - path: /SASRetrievalAgentManager/api(/|$)(.*)
      pathType: ImplementationSpecific
  # -- Paths configuration (used when useGlobal is true)
  paths:
  - path: /SASRetrievalAgentManager/api(/|$)(.*)
    pathType: ImplementationSpecific
  # -- TLS configuration for ingress
  tls: []
    # - secretName: ""
    #   hosts:
    #     - ""

# -- The resources to allocate for the container
resources:
  # -- Resource limits for the container
  limits:
    # -- CPU limit
    cpu: 2
    # -- Memory limit
    memory: 35Gi
  # -- Resource requests for the container
  requests:
    # -- CPU request
    cpu: 500m
    # -- Memory request
    memory: 20Gi

# -- Liveness probe configuration
livenessProbe:
  # -- Number of consecutive failures required to mark container as not ready
  failureThreshold: 15
  # -- HTTP GET probe configuration for liveness
  httpGet:
    # -- Path to probe for liveness
    path: /SASRetrievalAgentManager/api/v1/health/liveness
    port: http
    scheme: HTTP
  # -- How often to perform the probe
  periodSeconds: 10
  # -- Initial delay before starting probes
  initialDelaySeconds: 120
  # -- Minimum consecutive successes for the probe to be considered successful
  successThreshold: 1
  # -- Timeout for the probe
  timeoutSeconds: 1

# -- Readiness probe configuration
readinessProbe:
  # -- Number of consecutive failures required to mark container as not ready
  failureThreshold: 5
  # -- HTTP GET probe configuration for readiness
  httpGet:
    # -- Path to probe for readiness
    path: /SASRetrievalAgentManager/api/v1/health/readiness
    port: http
    scheme: HTTP
  # -- How often to perform the probe
  periodSeconds: 10
  # -- Initial delay before starting probes
  initialDelaySeconds: 120
  # -- Minimum consecutive successes for the probe to be considered successful
  successThreshold: 1
  # -- Timeout for the probe
  timeoutSeconds: 1

# -- Horizontal Pod Autoscaler configuration
autoscaling:
  # -- Enable horizontal pod autoscaling
  enabled: false
  # -- Maximum number of replicas
  maxReplicas: 100
  # -- Minimum number of replicas
  minReplicas: 1
  # -- Target CPU utilization percentage for scaling
  targetCPUUtilizationPercentage: 80

# -- Additional volumes on the output Deployment definition
volumes: []

# -- Additional volumeMounts on the output Deployment definition
volumeMounts: []

# -- Node labels for pod assignment
nodeSelector: {}

# -- Tolerations for pod assignment
tolerations: []

# -- Map of node/pod affinities
affinity:
  nodeAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 1
      preference:
        matchExpressions:
        - key: sas.com/deployment
          operator: In
          values:
          - sas-retrieval-agent-manager
    - weight: 2
      preference:
        matchExpressions:
        - key: workload.sas.com/class
          operator: In
          values:
          - ram

# -- Global configuration for SAS Retrieval Agent Manager and related services
global:
  # -- Configuration settings
  configuration:
    # -- API-specific configuration
    api:
      # -- Whether to use old license format
      useOldLicense: 'False'
      # -- License content (if not using secret)
      license: ""
      # -- Path to license secret mount
      license_secret_path: /mnt/config/license
      # -- Name of the license secret
      license_secret: "license-secret"
      # -- Log level for the API (DEBUG, INFO, WARNING, ERROR)
      log_level: INFO
      # -- Enable development mode features
      enable_dev_mode: 'False'
      # -- Enable profiling capabilities
      enable_profiling: 'False'
      # -- Number of worker processes
      num_workers: 4
      # -- SSL verification setting
      sslVerify: 'True'
      # -- Base path for API endpoints
      base_path: /SASRetrievalAgentManager/api
      # -- Latest API version
      latest_version: v1

      # -- Azure integration settings for API and identity management
      azure_settings:
        openAI:
          # -- Default API version for Azure OpenAI service (format: YYYY-MM-DD)
          default_api_version: "2024-10-21"
        azure_identity:
          # -- Enable Azure AD identity integration (true/false)
          enabled: false
          # -- Keyword used to identify Azure identity tokens in requests
          token_keyword: "AZURE_IDENTITY"
          # -- OAuth2 scope for Azure Cognitive Services authentication
          scope: "https://cognitiveservices.azure.com/.default"
          # -- Azure AD client ID for authentication (leave blank to disable)
          client_id: ""

    # -- Keycloak integration configuration
    keycloak:
      # -- Path to Keycloak configuration secret mount
      secret_path: /mnt/config/keycloak

    # -- GPG configuration for encryption/decryption
    gpg:
      # -- Path to GPG private key secret mount
      private_key_path: /mnt/config/gpg_key
      # -- Path to GPG passphrase secret mount
      passphrase_path: /mnt/config/gpg_passphrase

    # -- Evaluation service configuration
    eval:
      # -- Container image configuration for evaluation service
      image:
        repo:
          # -- Container registry base URL for evaluation service
          base: cr.sas.com
          # -- Container image path/name for evaluation service
          path: cdp-release-x64_oci_linux_2-docker-latest/sas-retrieval-agent-manager-evaluation
        # -- Container image tag for evaluation service
        tag: 1.3.0-20250829.1756499144702

    # -- Plugin agent configuration
    plugin:
      # -- Container image configuration for plugin agent
      image:
        repo:
          # -- Container registry base URL for plugin agent
          base: cr.sas.com
          # -- Container image path/name for plugin agent
          path: cdp-release-x64_oci_linux_2-docker-latest/sas-retrieval-agent-manager-agent
        # -- Container image tag for plugin agent
        tag: 1.4.0-20250829.1756485861996

    # -- Swagger UI configuration
    swagger:
      # -- Enable Swagger UI for API documentation
      enabled: true

    # -- Vectorization Hub (VHub) configuration
    vhub:
      # -- AWS certificate secret name (if using AWS)
      postgreSQLCertSecret: <your_PSQL_cert_secret>
      # -- Available hardware configuration for processing
      availableHardware:
        # -- Execution providers for ML/AI processing
        execution_providers:
        - cpu
        - openvino
        # -- CPU requirements for jobs
        job_req_cpu:
          # -- Default CPU allocation for jobs
          default: 6
          # -- Maximum CPU allocation for jobs
          max: 6
          # -- Minimum CPU allocation for jobs
          min: 1
        # -- Memory requirements for jobs
        job_req_mem:
          # -- Default memory allocation for jobs
          default: 32Gi
          # -- Maximum memory allocation for jobs
          max: 48Gi
          # -- Minimum memory allocation for jobs
          min: 16Gi
          # -- Model-specific memory defaults
          model_default:
            all-MiniLM-L6-v2: 16Gi
            distiluse-base-multilingual-cased-v2: 16Gi
            GTE-ModernColBERT-v1: 24Gi
            nomic-embed-text-v2-moe: 32Gi
        # -- CPU requirements for plugins
        plugin_req_cpu:
          # -- Default CPU allocation for plugins
          default: 2
          # -- Maximum CPU allocation for plugins
          max: 6
          # -- Minimum CPU allocation for plugins
          min: 1
        # -- Memory requirements for plugins
        plugin_req_mem:
          # -- Default memory allocation for plugins
          default: 4Gi
          # -- Maximum memory allocation for plugins
          max: 16Gi
          # -- Minimum memory allocation for plugins
          min: 1Gi
        # -- OpenVINO device types supported
        openvino_device_type:
        - CPU_FP32
        # -- Supported OCR languages by engine
        supported_ocr_languages:
          # -- Languages supported by PaddleOCR
          paddle:
          - eng       # English
          - chi_tra   # Chinese Traditional
          - dan       # Danish
          - deu       # German (Deutsch)
          - spa       # Spanish
          - fra       # French
          - ita       # Italian
          - nld       # Dutch (Nederlands)
          - pol       # Polish
          - por       # Portuguese
          # -- Languages supported by Tesseract
          tesseract:
          - eng       # English
          - chi_tra   # Chinese Traditional
          - jpn       # Japanese
          - dan       # Danish
          - deu       # German (Deutsch)
          - spa       # Spanish
          - fra       # French
          - ita       # Italian
          - nld       # Dutch (Nederlands)
          - pol       # Polish
          - por       # Portuguese
          - chi_sim   # Chinese Simplified
          - osd       # Orientation and Script Detection
          - equ       # Math/Equation Detection
      # -- Container image configuration for vectorization hub
      image:
        repo:
          # -- Container registry base URL for vectorization hub
          base: cr.sas.com
          # -- Container image path/name for vectorization hub
          path: cdp-release-x64_oci_linux_2-docker-latest/sas-retrieval-agent-manager-vectorization-hub
        # -- Container image tag for vectorization hub
        tag: 1.3.2-20250829.1756486393177
      # -- Array of imagePullSecrets for vectorization hub
      imagePullSecrets: []
