apiVersion: v1
kind: ConfigMap
metadata:
  name: eval-config
  labels:
    {{- include "sas-retrieval-agent-manager-api.labels" . | nindent 4 }}
data:
  eval_runner_repo: "{{ .Values.global.configuration.eval.image.repo.base }}/{{ .Values.global.configuration.eval.image.repo.path }}"
  eval_runner_tag: {{ .Values.global.configuration.eval.image.tag }}
