{{- $repo_base := "" -}}
{{- if and (hasKey .Values "global") (hasKey .Values.global "image") (hasKey .Values.global.image "repo") (hasKey .Values.global.image.repo "base") -}}
  {{- $repo_base = .Values.global.image.repo.base | default .Values.global.configuration.eval.image.repo.base -}}
{{- else -}}
  {{- $repo_base = .Values.global.configuration.eval.image.repo.base -}}
{{- end -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: eval-config
  labels:
    {{- include "sas-retrieval-agent-manager-api.labels" . | nindent 4 }}
data:
  eval_runner_repo: "{{ $repo_base }}/{{ .Values.global.configuration.eval.image.repo.path }}"
  eval_runner_tag: {{ .Values.global.configuration.eval.image.tag }}