apiVersion: v1
kind: Service
metadata:
  name: '{{ include "sas-retrieval-agent-manager-api.fullname" . }}-noauth'
  labels:
    {{- include "sas-retrieval-agent-manager-api.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: noauth-http
      protocol: TCP
      name: noauth-http
  selector:
    {{- include "sas-retrieval-agent-manager-api.selectorLabels" . | nindent 4 }}