{{- if .Values.serviceAccount.create -}}
{{- $azureEnabled := .Values.global.configuration.api.azure_settings.azure_identity.enabled }}
{{- $clientId := .Values.global.configuration.api.azure_settings.azure_identity.client_id }}
{{- $baseAnnotations := .Values.serviceAccount.annotations | default (dict) }}
{{- if $azureEnabled }}
  {{- $_ := set $baseAnnotations "azure.workload.identity/client-id" $clientId }}
{{- end }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "sas-retrieval-agent-manager-api.serviceAccountName" . }}
  labels:
    {{- include "sas-retrieval-agent-manager-api.labels" . | nindent 4 }}
  {{- with $baseAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
{{- end }}