apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-config
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
data:
  namespace: {{ .Release.Namespace }}
  service: {{ include "keycloak.fullname" . }}
  host: {{ if .Values.ingress.useGlobal -}}
          "{{ .Values.global.domain }}"
       {{- else -}}
          "{{ with (first .Values.ingress.hosts) }}{{ .host }}{{ end }}"
       {{- end }}
  basePath: {{ if .Values.ingress.useGlobal -}}
          "{{ regexReplaceAll "\\(.*" (first .Values.ingress.paths).path "" }}"
       {{- else -}}
          "{{ with (first .Values.ingress.hosts) }}{{ with (first .paths) }}{{ regexReplaceAll "\\(.*" .path "" }}{{ end }}{{ end }}"
       {{- end }}
  url: {{ if .Values.ingress.useGlobal -}}
          "https://{{ .Values.global.domain }}{{ regexReplaceAll "\\(.*" (first .Values.ingress.paths).path "" }}"
       {{- else -}}
          "https://{{ with (first .Values.ingress.hosts) }}{{ .host }}{{ with (first .paths) }}{{ regexReplaceAll "\\(.*" .path "" }}{{ end }}{{ end }}"
       {{- end }}
