---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-admin-secret
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
type: Opaque
stringData:
  user: {{ .Values.global.configuration.keycloak.keycloakAdmin | quote }}
  password: {{ .Values.global.configuration.keycloak.keycloakAdminPassword | quote }}
