---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-client-secret
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
type: Opaque
stringData:
  url: "http://{{ include "keycloak.fullname" . }}:{{ .Values.service.port }}"
  oauthUrl: {{ if .Values.ingress.useGlobal -}}
          "https://{{ .Values.global.domain }}{{ regexReplaceAll "\\(.*" (first .Values.oauthProxy.ingress.paths).path "" }}"
       {{- else -}}
          "https://{{ with (first .Values.oauthProxy.ingress.hosts) }}{{ .host }}/{{ with (first .paths) }}{{ regexReplaceAll "\\(.*" .path "" }}{{ end }}{{ end }}"
       {{- end }}
  realm: {{ .Values.global.configuration.keycloak.realm | quote }}
  sv-client-id: {{ .Values.global.configuration.keycloak.clientId | quote }}
  sv-client-secret: {{ include "keycloak.clientSecret" . | quote }}
