apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "keycloak.fullname" . }}-kc-scripts
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}

data:
  init.sh: |-
    PSQL=$(which psql)

    until pg_isready -h $POSTGRES_HOST -p $POSTGRES_PORT -U $POSTGRES_USER;
    do
      echo "Waiting for database to be ready ...";
      sleep 2;
    done;
    echo "The database server is ready";

    until psql -h $POSTGRES_HOST -p $POSTGRES_PORT -U $POSTGRES_USER -d $POSTGRES_DB -c "SELECT 1";
    do
      echo "Waiting for database...";
      sleep 5;
    done;
    echo "The database is present";