
{{if .Values.ingress.domain }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ui.fullname" . }}
  labels:
    {{- include "ui.labels" . | nindent 4 }}
spec:
  {{- if not .Values.ui.autoscaling.enabled }}
  replicas: {{ .Values.ui.replicaCount }}
  {{- end }}
  {{- with .Values.ui.strategy }}
  strategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "ui.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.ui.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "ui.labels" . | nindent 8 }}
        {{- with .Values.ui.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.images.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "ui.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.ui.podSecurityContext | nindent 8 }}
      initContainers:
        {{- include "oauth2-proxy.sidecar.init" . | nindent 8 }}
      containers:
        - name: ui
          securityContext:
            {{- toYaml .Values.ui.securityContext | nindent 12 }}
          image: "{{- include "images.ui" . -}}"
          imagePullPolicy: {{ .Values.images.ui.pullPolicy }}
          env:
            - name: LOGOUT_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ printf "%s-proxy-config" (include "oauth2-proxy.fullname" .) }}
                  key: logoutUrl
            - name: POSTGREST_SERVICE
              valueFrom:
                configMapKeyRef:
                  name: {{ printf "%s-config" (include "postgrest.fullname" .) }}
                  key: service
            - name: SSL_VERIFY
              value: '{{ index .Values.ui.config "sslVerify" }}'
          ports:
            - name: http
              containerPort: {{ .Values.ui.service.port }}
              protocol: TCP
          livenessProbe:
            {{ include "ui.livenessProbe" . | nindent 12 }}
          readinessProbe:
            {{ include "ui.readinessProbe" . | nindent 12 }}
          resources:
            {{- toYaml .Values.ui.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /var/cache/nginx
              name: cache
            - mountPath: /var/run
              name: run
          {{- with .Values.ui.volumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
        {{- include "oauth2-proxy.sidecar" (dict "Root" . "upstreamPort" .Values.ui.service.port) | nindent 8 }}
      volumes:
        {{- include "oauth2-proxy.sidecar.volumes" . | nindent 8 }}
        - name: cache
          emptyDir: {}
        - name: run
          emptyDir: {}
      {{- with .Values.ui.volumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.ui.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.ui.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.ui.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
