apiVersion: v1
kind: Service
metadata:
  name: {{ include "ui.fullname" . }}
  labels:
    {{- include "ui.labels" . | nindent 4 }}
spec:
  type: {{ .Values.ui.service.type }}
  ports:
    - port: {{ .Values.ui.service.port }}
      targetPort: oauth2-proxy0
      protocol: TCP
      name: http
  selector:
    {{- include "ui.selectorLabels" . | nindent 4 }}
