{{- if .Values.ingress.enabled -}}
{{- $logoutUrl := "" -}}

{{- if and .Values.ingress.oauthProxy.paths .Values.ingress.keycloak.paths -}}
{{- $oauthProxyPath := first .Values.ingress.oauthProxy.paths -}}
{{- $keycloakPath := first .Values.ingress.keycloak.paths -}}
{{- $postLogoutUri := printf "https://%s" .Values.ingress.domain -}}
{{- $logoutRedirect := printf "https://%s%s/realms/%s/protocol/openid-connect/logout?client_id=%s&post_logout_redirect_uri=%s" .Values.ingress.domain $keycloakPath .Values.iam.keycloak.config.realm .Values.iam.keycloak.config.clientId $postLogoutUri -}}
{{- $logoutUrl = printf "https://%s%s/sign_out?rd=%s" .Values.ingress.domain $oauthProxyPath ($logoutRedirect | urlquery) -}}
{{- end -}}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-proxy-config" (include "oauth2-proxy.fullname" .) }}
  labels:
    {{- include "oauth2-proxy.labels" . | nindent 4 }}
data:
  namespace: {{ .Release.Namespace }}
  service: {{ include "oauth2-proxy.fullname" . }}
  logoutUrl: {{ $logoutUrl | quote }}
{{- end -}}
