{{- if .Values.db.migration.config.llmHydration.enabled -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "db-migration.fullname" . }}-llm-hydration
  labels:
    {{- include "db-migration.labels" . | nindent 4 }}
    ram-base-job: "true"
  annotations:
    argocd.argoproj.io/sync-options: Skip
    helm.sh/hook-weight: "0"
    helm.sh/hook: post-install
spec:
  template:
    metadata:
      {{- with .Values.db.migration.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "db-migration.labels" . | nindent 8 }}
        {{- with .Values.db.migration.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.images.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "db-migration.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.db.migration.podSecurityContext | nindent 8 }}
      initContainers:
        - name: wait-for-llm-table
          command:
            - "/bin/sh"
            - "-c"
            - "/scripts/wait_for_llm_table.sh"
          image: "{{- include "images.postgres" . -}}"
          imagePullPolicy: {{ .Values.images.postgres.pullPolicy }}
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  key: user
                  name: {{ printf "%s-migration-db-credentials" (include "retrieval-agent-manager.fullname" .) }}
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: {{ printf "%s-migration-db-credentials" (include "retrieval-agent-manager.fullname" .) }}
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  key: host
                  name: {{ printf "%s-db-connection" (include "retrieval-agent-manager.fullname" .) }}
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  key: port
                  name: {{ printf "%s-db-connection" (include "retrieval-agent-manager.fullname" .) }}
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  key: db
                  name: {{ printf "%s-db-application" (include "retrieval-agent-manager.fullname" .) }}
            - name: DB_SCHEMA
              valueFrom:
                configMapKeyRef:
                  key: schema
                  name: {{ printf "%s-db-application" (include "retrieval-agent-manager.fullname" .) }}
          securityContext:
            {{- toYaml .Values.db.migration.securityContext | nindent 12 }}
          resources:
            {{- toYaml .Values.db.migration.resources | nindent 12 }}
          volumeMounts:
            - mountPath: "/scripts"
              name: scripts
              readOnly: true
      containers:
        - name: llm-hydration
          image: "{{- include "images.postgres" . -}}"
          imagePullPolicy: {{ .Values.images.postgres.pullPolicy }}
          command:
            - "/bin/bash"
            - "-c"
            - "/scripts/llm_hydration_initialization.sh"
          securityContext:
            {{- toYaml .Values.db.migration.securityContext | nindent 12 }}
          resources:
            {{- toYaml .Values.db.migration.resources | nindent 12 }}
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  key: host
                  name: {{ printf "%s-db-connection" (include "retrieval-agent-manager.fullname" .) }}
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  key: port
                  name: {{ printf "%s-db-connection" (include "retrieval-agent-manager.fullname" .) }}
            - name: USER
              valueFrom:
                secretKeyRef:
                  key: user
                  name: {{ printf "%s-migration-db-credentials" (include "retrieval-agent-manager.fullname" .) }}
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: {{ printf "%s-migration-db-credentials" (include "retrieval-agent-manager.fullname" .) }}
            - name: LLM_KEY
              valueFrom:
                secretKeyRef:
                  key: apiKey
                  name: llm-key
          volumeMounts:
            - mountPath: "/scripts"
              name: scripts
              readOnly: true
            - name: db-config
              mountPath: /config/db-config
              readOnly: true
      restartPolicy: OnFailure
      {{- with .Values.db.migration.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.db.migration.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.db.migration.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: scripts
          configMap:
            name: {{ include "db-migration.fullname" . }}-scripts
            defaultMode: 0777
        - name: db-config
          configMap:
            name: {{ printf "%s-db-application" (include "retrieval-agent-manager.fullname" .) }}
  backoffLimit: 10
{{- end -}}
