{{- if .Values.db.migration.config.llmHydration.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: llm-key
  labels:
    {{- include "db-migration.labels" . | nindent 4 }}
stringData:
  apiKey: {{ .Values.db.migration.config.llmHydration.key | b64dec | quote }}
{{- end }}
