apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "db-migration.fullname" . }}
  labels:
    {{- include "db-migration.labels" . | nindent 4 }}
    ram-base-job: "true"
  annotations:
    argocd.argoproj.io/sync-options: Skip
spec:
  template:
    metadata:
      {{- with .Values.db.migration.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "db-migration.labels" . | nindent 8 }}
        {{- with .Values.db.migration.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.images.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "db-migration.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.db.migration.podSecurityContext | nindent 8 }}
      initContainers:
        - name: wait-for-db
          command:
            - "/bin/sh"
            - "-c"
            - "/scripts/wait_for_database.sh"
          image: "{{- include "images.postgres" . -}}"
          imagePullPolicy: {{ .Values.images.postgres.pullPolicy }}
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  key: user
                  name: {{ printf "%s-migration-db-credentials" (include "retrieval-agent-manager.fullname" .) }}
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: {{ printf "%s-migration-db-credentials" (include "retrieval-agent-manager.fullname" .) }}
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  key: host
                  name: {{ printf "%s-db-connection" (include "retrieval-agent-manager.fullname" .) }}
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  key: port
                  name: {{ printf "%s-db-connection" (include "retrieval-agent-manager.fullname" .) }}
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  key: db
                  name: {{ printf "%s-db-application" (include "retrieval-agent-manager.fullname" .) }}
            - name: DB_SCHEMA
              valueFrom:
                configMapKeyRef:
                  key: schema
                  name: {{ printf "%s-db-application" (include "retrieval-agent-manager.fullname" .) }}
          securityContext:
            {{- toYaml .Values.db.migration.securityContext | nindent 12 }}
          resources:
            {{- toYaml .Values.db.migration.resources | nindent 12 }}
          volumeMounts:
            - mountPath: "/scripts"
              name: scripts
              readOnly: true
        - name: wait-for-monitoring-db
          command:
            - "/bin/sh"
            - "-c"
            - "/scripts/wait_for_database.sh"
          image: "{{- include "images.postgres" . -}}"
          imagePullPolicy: {{ .Values.images.postgres.pullPolicy }}
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  key: user
                  name: {{ printf "%s-migration-db-credentials" (include "retrieval-agent-manager.fullname" .) }}
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: {{ printf "%s-migration-db-credentials" (include "retrieval-agent-manager.fullname" .) }}
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  key: host
                  name: {{ printf "%s-db-connection" (include "retrieval-agent-manager.fullname" .) }}
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  key: port
                  name: {{ printf "%s-db-connection" (include "retrieval-agent-manager.fullname" .) }}
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  key: db
                  name: {{ printf "%s-db-monitoring" (include "retrieval-agent-manager.fullname" .) }}
            - name: DB_SCHEMA
              valueFrom:
                configMapKeyRef:
                  key: schema
                  name: {{ printf "%s-db-monitoring" (include "retrieval-agent-manager.fullname" .) }}
          securityContext:
            {{- toYaml .Values.db.migration.securityContext | nindent 12 }}
          resources:
            {{- toYaml .Values.db.migration.resources | nindent 12 }}
          volumeMounts:
            - mountPath: "/scripts"
              name: scripts
              readOnly: true
      containers:
        - name: db-migration
          image: "{{- include "images.goose" . -}}"
          imagePullPolicy: {{ .Values.images.goose.pullPolicy }}
          securityContext:
            {{- toYaml .Values.db.migration.securityContext | nindent 12 }}
          resources:
            {{- toYaml .Values.db.migration.resources | nindent 12 }}
          volumeMounts:
            - name: embedding-models
              mountPath: "/mnt/embedding_models"
              readOnly: false
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  key: host
                  name: {{ printf "%s-db-connection" (include "retrieval-agent-manager.fullname" .) }}
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  key: port
                  name: {{ printf "%s-db-connection" (include "retrieval-agent-manager.fullname" .) }}
            - name: DB_SSLMODE
              valueFrom:
                configMapKeyRef:
                  key: sslmode
                  name: {{ printf "%s-db-connection" (include "retrieval-agent-manager.fullname" .) }}
            - name: EMBEDDING_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  key: user
                  name: {{ printf "%s-embedding-db-credentials" (include "retrieval-agent-manager.fullname" .) }}
            - name: MODELS_DESTINATION_PATH
              valueFrom:
                configMapKeyRef:
                  key: models_destination_dir
                  name: {{ printf "%s-embedding-config" (include "api.fullname" .) }}
            - name: APP_DB_NAME
              valueFrom:
                configMapKeyRef:
                  key: db
                  name: {{ printf "%s-db-application" (include "retrieval-agent-manager.fullname" .) }}
            - name: APP_DB_SCHEMA
              valueFrom:
                configMapKeyRef:
                  key: schema
                  name: {{ printf "%s-db-application" (include "retrieval-agent-manager.fullname" .) }}
            - name: MONITORING_DB_NAME
              valueFrom:
                configMapKeyRef:
                  key: db
                  name: {{ printf "%s-db-monitoring" (include "retrieval-agent-manager.fullname" .) }}
            - name: MONITORING_DB_SCHEMA
              valueFrom:
                configMapKeyRef:
                  key: schema
                  name: {{ printf "%s-db-monitoring" (include "retrieval-agent-manager.fullname" .) }}
            - name: DB_SECRETS_PUBLIC_KEY
              valueFrom:
                configMapKeyRef:
                  key: public
                  name: {{ printf "%s-public-key" (include "gpg.fullname" .) }}
            - name: MIGRATE_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  key: user
                  name: {{ printf "%s-migration-db-credentials" (include "retrieval-agent-manager.fullname" .) }}
            - name: MIGRATE_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: {{ printf "%s-migration-db-credentials" (include "retrieval-agent-manager.fullname" .) }}
            - name: OTEL_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  key: user
                  name: {{ printf "%s-otel-db-credentials" (include "retrieval-agent-manager.fullname" .) }}
            - name: PGREST_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  key: user
                  name: {{ printf "%s-application-db-credentials" (include "retrieval-agent-manager.fullname" .) }}
            - name: VJOB_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  key: user
                  name: {{ printf "%s-vector-job-db-credentials" (include "retrieval-agent-manager.fullname" .) }}
            - name: DB_AUTH_ROLE_ADMINS
              valueFrom:
                configMapKeyRef:
                  key: adminRole
                  name: {{ printf "%s-app-roles" (include "retrieval-agent-manager.fullname" .) }}
            - name: DB_AUTH_ROLE_USERS
              valueFrom:
                configMapKeyRef:
                  key: userRole
                  name: {{ printf "%s-app-roles" (include "retrieval-agent-manager.fullname" .) }}
            {{- if .Values.db.init.config.timescale.enabled }}
            - name: ENABLE_TIMESCALE
              valueFrom:
                configMapKeyRef:
                  key: enabled
                  name: {{ printf "%s-db-timescale" (include "retrieval-agent-manager.fullname" .) }}
            {{- end }}
            {{- if .Values.db.init.config.vectorStore.enabled }}
            - name: ENABLE_VECTOR_STORE
              valueFrom:
                configMapKeyRef:
                  key: enabled
                  name: {{ printf "%s-db-vector-store" (include "retrieval-agent-manager.fullname" .) }}
            - name: VECTOR_DB_NAME
              valueFrom:
                configMapKeyRef:
                  key: db
                  name: {{ printf "%s-db-vector-store" (include "retrieval-agent-manager.fullname" .) }}
            - name: VECTOR_DB_SCHEMA
              valueFrom:
                configMapKeyRef:
                  key: schema
                  name: {{ printf "%s-db-vector-store" (include "retrieval-agent-manager.fullname" .) }}
            - name: VECTOR_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  key: user
                  name: {{ printf "%s-vector-store-db-credentials" (include "retrieval-agent-manager.fullname" .) }}
            - name: VECTOR_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: {{ printf "%s-vector-store-db-credentials" (include "retrieval-agent-manager.fullname" .) }}
            {{- end }}
            {{- if .Values.db.init.config.weaviate.enabled }}
            - name: ENABLE_LOCAL_WEAVIATE
              valueFrom:
                configMapKeyRef:
                  key: enabled
                  name: {{ printf "%s-db-weaviate" (include "retrieval-agent-manager.fullname" .) }}
            {{- end }}
      restartPolicy: OnFailure
      {{- with .Values.db.migration.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.db.migration.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.db.migration.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: scripts
          configMap:
            name: {{ include "db-migration.fullname" . }}-scripts
            defaultMode: 0555
        - name: embedding-models
          persistentVolumeClaim:
            claimName: embedding-pv
  backoffLimit: 1000
