{{- if .Values.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "filebrowser.fullname" . }}
  labels:
    {{- include "filebrowser.labels" . | nindent 4 }}
data:
  .filebrowser.json: |
    {{- .Values.config | toPrettyJson | nindent 4 }}
{{- end -}}