{{- if .Values.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "filebrowser.fullname" . }}
  labels:
    {{- include "filebrowser.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  {{- with .Values.strategy }}
  strategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "filebrowser.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "filebrowser.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "filebrowser.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: init-db
          image: busybox
          command: ["sh", "-c", "touch /db/filebrowser.db && chown 1000:1000 /db/filebrowser.db"]
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: db
              mountPath: /db
      {{- with .Values.initContainers }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repo.base }}/{{ .Values.image.repo.path }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{- if .Values.securityContext.runAsUser }}
            - name: PUID
              value: {{ .Values.securityContext.runAsUser | quote }}
            {{- end }}
            {{- if .Values.securityContext.runAsGroup }}
            - name: PGID
              value: {{ .Values.securityContext.runAsGroup | quote }}
            {{- end }}
            - name: FB_BASEURL
              value: {{ .Values.config.baseURL }}
            - name: FB_DATABASE
              value: {{ .Values.config.database }}
            - name: FB_NOAUTH
              value: "true"
            - name: FB_PORT
              value: {{ .Values.config.port | quote }}
            - name: FB_ROOT
              value: {{ .Values.config.root }}
            - name: FB_LOG
              value: {{ .Values.config.log }}
          volumeMounts:
            - mountPath: /.filebrowser.json
              name: config
              subPath: .filebrowser.json
            - mountPath: "/db"
              name: db
            - mountPath: {{ .Values.rootDir.hostPath.path | default "/rootdir" }}
              name: rootdir
              readOnly: {{ .Values.rootDir.readOnly }}
          ports:
            - name: http
              containerPort: {{ .Values.config.port }}
              protocol: TCP
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ include "filebrowser.fullname" . }}
        - name: db
          {{- if .Values.db.pvc.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Values.db.pvc.existingClaim | default (printf "%s-%s" (include "filebrowser.fullname" .) "db" ) }}
          {{- else }}
          emptyDir: {}
          {{- end }}
        - name: rootdir
          {{- if eq .Values.rootDir.type "pvc" }}
          persistentVolumeClaim:
            claimName: {{ .Values.rootDir.pvc.existingClaim | default .Values.rootDir.pvc.name }}
            readOnly: {{ .Values.rootDir.readOnly }}
          {{- else if eq .Values.rootDir.type "hostPath" }}
          hostPath:
            path: {{ .Values.rootDir.hostPath.path }}
          {{- else }}
          emptyDir: {}
          {{- end }}
{{- end -}}