apiVersion: kueue.x-k8s.io/v1beta1
kind: ClusterQueue
metadata:
  name: "cluster-queue"
  labels:
    {{- include "sas-retrieval-agent-manager.labels" . | nindent 4 }}
spec:
  namespaceSelector:
    matchLabels:
      kubernetes.io/metadata.name: "{{ .Release.Namespace }}"
  resourceGroups:
  - coveredResources: ["cpu", "memory", "pods"]
    flavors:
    - name: "sas-retrieval-agent-manager"
      resources:
      - name: "cpu"
        nominalQuota: {{ .Values.global.configuration.kueue.cpuQuota | default "32" }}
      - name: "memory"
        nominalQuota: {{ .Values.global.configuration.kueue.memoryQuota | default "128Gi" }}
      - name: "pods"
        nominalQuota: {{ .Values.global.configuration.kueue.podQuota | default "6" }}
