{{- if .Values.swagger.enabled -}}
{{- if .Values.swagger.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "postgrest.swagger.serviceAccountName" . }}
  labels:
    {{- include "postgrest.swagger.labels" . | nindent 4 }}
  {{- with .Values.swagger.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.swagger.serviceAccount.automount }}
{{- end }}
{{- end }}
