apiVersion: v1
kind: Secret
metadata:
  name: gpg-passphrase
  labels:
    {{- include "gpg.labels" . | nindent 4 }}
stringData:
  passphrase: {{ .Values.global.configuration.gpg.passphrase | quote }}
