{{if .Values.ingress.domain}}
{{- $keycloakPath := first .Values.ingress.keycloak.paths -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "keycloak.fullname" . }}-realm-update
  labels:
    ram-base-job: "true"
    app.kubernetes.io/version: {{ .Chart.Version | quote }}
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-weight: "10"
    helm.sh/hook-delete-policy: before-hook-creation
spec:
  backoffLimit: 3
  ttlSecondsAfterFinished: 300
  template:
    spec:
      initContainers:
        - command:
            - /bin/sh
            - -c
            - |
              while [ $(curl -sw '%{http_code}' "http://{{ include "keycloak.fullname" . | lower }}:{{ .Values.iam.keycloak.service.port }}{{ $keycloakPath }}/realms/{{ .Values.iam.keycloak.config.realm}}" -o /dev/null) -ne 200 ]; do
                echo "Waiting for ID provider to reach ready state...";
                sleep 15;
              done
          image: "{{- include "images.kubectl" . -}}"
          imagePullPolicy: {{ .Values.images.kubectl.pullPolicy }}
          name: idp-ready
          resources:
            limits:
              cpu: 50m
              memory: 32Mi
            requests:
              cpu: 50m
              memory: 32Mi
          securityContext:
            {{- toYaml .Values.iam.keycloak.securityContext | nindent 12 }}
      containers:
        - name: update-realm
          image: "{{- include "images.keycloak" . -}}"
          imagePullPolicy: {{ .Values.images.keycloak.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ include "keycloak.fullname" . }}-realm-update-env
                optional: false
          env:
            - name: KCADM_CFG_PATH
              value: "/workdir/kcadm.config"
          securityContext:
            {{- toYaml .Values.iam.keycloak.securityContext | nindent 12 }}
          resources:
            limits:
              cpu: 500m
              memory: 768Mi
            requests:
              cpu: 50m
              memory: 128Mi
          command:
            - "/updates/apply.sh"
          volumeMounts:
            - mountPath: /admin
              name: admin-credentials
              readOnly: true
            - mountPath: /updates
              name: realm-update-scripts
            - mountPath: /workdir
              name: workdir
      restartPolicy: OnFailure
      serviceAccountName: {{ include "keycloak.serviceAccountName" . }}-realm-update
      volumes:
        - name: admin-credentials
          secret:
            secretName: {{ printf "%s-admin-secret" (include "keycloak.fullname" .) }}
            items:
              - key: user
                path: username
              - key: password
                path: password
        - name: realm-update-scripts
          configMap:
            defaultMode: 0755
            name: {{ include "keycloak.fullname" . }}-realm-update-scripts
        - name: workdir
          emptyDir: {}
{{- end }}
