apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-agent-config" (include "api.fullname" .) }}
  labels:
    {{- include "api.labels" . | nindent 4 }}
data:
  agent_runner_repo: {{ printf "%s/%s" (include "images.agent.repo.base" .)  (include "images.agent.repo.path" .) }}
  agent_runner_tag: {{ include "images.agent.tag" . | quote }}
