{{- $basePathWithLeadingSlash := .Values.api.config.base_path | toString | trimSuffix "/" }}
{{- if eq $basePathWithLeadingSlash "/" }}
{{- $basePathWithLeadingSlash = "" }}
{{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-config" (include "api.fullname" .) }}
  labels:
    {{- include "api.labels" . | nindent 4 }}
data:
  namespace: {{ .Release.Namespace }}
  service: {{ include "api.fullname" . }}
  noauth-service: '{{ include "api.fullname" . }}-noauth'
  url: "https://{{ .Values.ingress.domain }}{{ first .Values.ingress.api.paths }}"
  docsUrl: "https://{{ .Values.ingress.domain }}{{ first .Values.ingress.api.paths }}/docs"
  base_path: {{ $basePathWithLeadingSlash | quote }}
  inClusterUrl: "http://{{ include "api.fullname" . }}:{{ .Values.api.service.port }}{{ $basePathWithLeadingSlash }}/{{ .Values.api.latest_version }}"
  noauthInClusterUrl: "http://{{ include "api.fullname" . }}-noauth:{{ .Values.api.service.port }}{{ $basePathWithLeadingSlash }}/{{ .Values.api.latest_version }}"
  spawn_sa_name: {{ include "api.spawn.serviceAccountName" . }}
{{- if .Values.integrations.trustedCerts.enabled }}
  trusted_certs_path: "/mnt/config/certs/trusted-certs.pem"
  {{- if eq (.Values.integrations.trustedCerts.type | lower) "configmap" }}
  trusted_certs_configmap: {{ .Values.integrations.trustedCerts.name }}
  {{- else if eq (.Values.integrations.trustedCerts.type | lower) "secret" }}
  trusted_certs_secret: {{ .Values.integrations.trustedCerts.name }}
  {{- end }}
{{- end }}
