apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-evaluation-config" (include "api.fullname" .) }}
  labels:
    {{- include "api.labels" . | nindent 4 }}
data:
  eval_runner_repo: {{ printf "%s/%s" (include "images.eval.repo.base" .)  (include "images.eval.repo.path" .) }}
  eval_runner_tag: {{ include "images.eval.tag" .  | quote }}
