{{- if .Values.api.config.license }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-license" (include "retrieval-agent-manager.fullname" .) }}
  labels:
    {{- include "api.labels" . | nindent 4 }}
data:
  {{- with .Values.api.config.license }}
  # License: {{ . | b64enc | quote }}
  license.jwt: {{ . | b64enc | quote }}
  {{- end }}
{{- end }}