apiVersion: v1
kind: Service
metadata:
  name: '{{ include "api.fullname" . }}-noauth'
  labels:
    {{- include "api.labels" . | nindent 4 }}
spec:
  type: {{ .Values.api.service.type }}
  ports:
    - port: {{ .Values.api.service.port }}
      targetPort: noauth-http
      protocol: TCP
      name: noauth-http
  selector:
    {{- include "api.selectorLabels" . | nindent 4 }}
