{{- if .Values.api.serviceAccount.create -}}
{{- $azureEnabled := .Values.api.config.azure_settings.azure_identity.enabled }}
{{- $clientId := .Values.api.config.azure_settings.azure_identity.client_id }}
{{- $baseAnnotations := .Values.api.serviceAccount.annotations | default (dict) }}
{{- if $azureEnabled }}
  {{- $_ := set $baseAnnotations "azure.workload.identity/client-id" $clientId }}
{{- end }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "api.serviceAccountName" . }}
  labels:
    {{- include "api.labels" . | nindent 4 }}
  {{- with $baseAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.api.serviceAccount.automount }}
{{- end }}