apiVersion: v1
kind: Service
metadata:
  name: {{ include "api.fullname" . }}
  labels:
    {{- include "api.labels" . | nindent 4 }}
spec:
  type: {{ .Values.api.service.type }}
  ports:
    # Main port routes to OAuth2 proxy sidecar (port 4180)
    # OAuth2 proxy then forwards authenticated requests to app on localhost:8765
    - port: {{ .Values.api.service.port }}
      targetPort: oauth2-proxy0
      protocol: TCP
      name: http
  selector:
    {{- include "api.selectorLabels" . | nindent 4 }}