apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-vector-hub-config" (include "api.fullname" .) }}
  labels:
    {{- include "api.labels" . | nindent 4 }}
data:
  vhub_repository: "{{- include "images.vectorizationHub.repo.base" . -}}/{{- include "images.vectorizationHub.repo.path" . -}}"
  vhub_tag: "{{- include "images.vectorizationHub.tag" . -}}"
  
  {{- with .Values.images.imagePullSecrets }}
  vhub_pull_secret: {{ (index . 0).name }}
  {{- end }}
  available_hardware: {{ .Values.vectorizationHub.config.availableHardware | toJson | quote }}
  vectorization_job_db_credentials: {{ printf "%s-vector-job-db-credentials" (include "retrieval-agent-manager.fullname" .) }}
  {{- if .Values.vectorizationHub.config.postgreSQLCertSecret | default .Values.vectorizationHub.config.awsCertSecret | quote }}
  postgresql_cert_secret: {{ .Values.vectorizationHub.config.postgreSQLCertSecret | default .Values.vectorizationHub.config.awsCertSecret | quote }}
  {{- end }}
