apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "postgrest.fullname" . }}
  labels:
    {{- include "postgrest.labels" . | nindent 4 }}
spec:
  {{- if not .Values.db.rest.autoscaling.enabled }}
  replicas: {{ .Values.db.rest.replicaCount }}
  {{- end }}
  {{- with .Values.db.rest.strategy }}
  strategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "postgrest.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.db.rest.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "postgrest.labels" . | nindent 8 }}
        {{- with .Values.db.rest.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      shareProcessNamespace: true
      {{- with .Values.images.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "postgrest.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.db.rest.podSecurityContext | nindent 8 }}
      initContainers:
        {{- include "wait-for-db.container" (dict "db" "application" "Root" .) | nindent 8 }}
        {{- include "wait-for-db.container" (dict "db" "monitoring" "Root" .) | nindent 8 }}
        {{- include "oauth2-proxy.sidecar.init" . | nindent 8 }}
      containers:
        - name: jwks-fetcher
          image: "{{- include "images.kubectl" . -}}"
          imagePullPolicy: {{ .Values.images.kubectl.pullPolicy }}
          command:
            - sh
            - -c
            - /scripts/jwks-fetcher.sh
          volumeMounts:
            - name: jwks
              mountPath: /jwks
            - name: scripts
              mountPath: /scripts
              readOnly: true
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 10m
              memory: 32Mi
        - name: postgrest
          command:
              - /bin/postgrest
          args:
              - /postgrest-config/postgrest.conf
          env:
            - name: PGRST_SERVER_PORT
              value: {{ .Values.db.rest.service.port | quote }}
            - name: PGRST_ADMIN_SERVER_PORT
              value: {{ .Values.db.rest.adminService.port | quote }}
            - name: PGUSER
              valueFrom:
                secretKeyRef:
                  name: {{ printf "%s-application-db-credentials" (include "retrieval-agent-manager.fullname" .) }}
                  key: user
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ printf "%s-application-db-credentials" (include "retrieval-agent-manager.fullname" .) }}
                  key: password
            - name: PGHOST
              valueFrom:
                configMapKeyRef:
                  name: {{ printf "%s-db-connection" (include "retrieval-agent-manager.fullname" .) }}
                  key: host
            - name: PGPORT
              valueFrom:
                configMapKeyRef:
                  name: {{ printf "%s-db-connection" (include "retrieval-agent-manager.fullname" .) }}
                  key: port
            - name: PGDATABASE
              valueFrom:
                configMapKeyRef:
                  name: {{ printf "%s-db-application" (include "retrieval-agent-manager.fullname" .) }}
                  key: db
            - name: PGRST_DB_SCHEMAS
              valueFrom:
                configMapKeyRef:
                  name: {{ printf "%s-db-application" (include "retrieval-agent-manager.fullname" .) }}
                  key: schema
          image: "{{- include "images.postgrest" . -}}"
          imagePullPolicy: {{ .Values.images.postgrest.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.db.rest.service.port }}
              protocol: TCP
            - name: admin
              containerPort: {{ .Values.db.rest.adminService.port }}
              protocol: TCP
          livenessProbe:
            {{- include "postgrest.livenessProbe" . | nindent 12 }}
          readinessProbe:
            {{- include "postgrest.readinessProbe" . | nindent 12 }}
          resources:
            {{- toYaml .Values.db.rest.resources | nindent 12 }}
          securityContext:
            {{- toYaml .Values.db.rest.securityContext | nindent 12 }}
          volumeMounts:
            - mountPath: "/config"
              name: scripts
              readOnly: true
            - mountPath: "/postgrest-config"
              name: configuration
              readOnly: true
            - mountPath: "/jwks"
              name: jwks
            {{- with .Values.db.rest.volumeMounts }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
        - name: postgrest-monitoring
          command:
            - /bin/postgrest
          args:
            - /postgrest-config/postgrest.conf
          env:
            - name: PGRST_SERVER_PORT
              value: {{ .Values.db.rest.monitoring.service.port | quote }}
            - name: PGRST_ADMIN_SERVER_PORT
              value: {{ .Values.db.rest.monitoring.adminService.port | quote }}
            - name: PGUSER
              valueFrom:
                secretKeyRef:
                  name: {{ printf "%s-monitoring-db-credentials" (include "retrieval-agent-manager.fullname" .) }}
                  key: user
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ printf "%s-monitoring-db-credentials" (include "retrieval-agent-manager.fullname" .) }}
                  key: password
            - name: PGHOST
              valueFrom:
                configMapKeyRef:
                  name: {{ printf "%s-db-connection" (include "retrieval-agent-manager.fullname" .) }}
                  key: host
            - name: PGPORT
              valueFrom:
                configMapKeyRef:
                  name: {{ printf "%s-db-connection" (include "retrieval-agent-manager.fullname" .) }}
                  key: port
            - name: PGDATABASE
              valueFrom:
                configMapKeyRef:
                  name: {{ printf "%s-db-monitoring" (include "retrieval-agent-manager.fullname" .) }}
                  key: db
            - name: PGRST_DB_SCHEMAS
              valueFrom:
                configMapKeyRef:
                  name: {{ printf "%s-db-monitoring" (include "retrieval-agent-manager.fullname" .) }}
                  key: schema
          image: "{{- include "images.postgrest" . -}}"
          imagePullPolicy: {{ .Values.images.postgrest.pullPolicy }}
          ports:
            - name: http-monitor
              containerPort: {{ .Values.db.rest.monitoring.service.port }}
              protocol: TCP
            - name: admin-monitor
              containerPort: {{ .Values.db.rest.monitoring.adminService.port }}
              protocol: TCP
          livenessProbe:
            {{- include "postgrest.livenessProbeMonitoring" . | nindent 12 }}
          readinessProbe:
            {{- include "postgrest.readinessProbeMonitoring" . | nindent 12 }}
          resources:
            {{- toYaml .Values.db.rest.resources | nindent 12 }}
          securityContext:
            {{- toYaml .Values.db.rest.securityContext | nindent 12 }}
          volumeMounts:
            - name: scripts
              readOnly: true
              mountPath: /config
            - name: configuration
              readOnly: true
              mountPath: /postgrest-config
            - name: jwks
              mountPath: /jwks
            {{- with .Values.db.rest.volumeMounts }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
        {{- include "oauth2-proxy.sidecar" (dict "Root" . "upstreamPort" .Values.db.rest.service.port "instance" 0) | nindent 8 }}
        {{- include "oauth2-proxy.sidecar" (dict "Root" . "upstreamPort" .Values.db.rest.monitoring.service.port "instance" 1) | nindent 8 }}
      volumes:
        {{- include "wait-for-db.volumes" (dict "db" "application" "Root" .) | nindent 8 }}
        {{- include "wait-for-db.volumes" (dict "db" "monitoring" "Root" .) | nindent 8 }}
        {{- include "oauth2-proxy.sidecar.volumes" . | nindent 8 }}
        - name: workdir
          emptyDir: {}
        - name: jwks
          emptyDir: {}
        - name: configuration
          configMap:
            name: {{ include "postgrest.fullname" . }}-configuration
        - name: scripts
          configMap:
            name: {{ include "postgrest.fullname" . }}-scripts
            defaultMode: 0777
        {{- with .Values.db.rest.volumes }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.db.rest.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.db.rest.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.db.rest.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
