apiVersion: v2
name: gpg
description: A Helm chart for GPG key management and cryptographic operations in Kubernetes
type: application
version: 1.1.0
appVersion: "1.3.6"

# Chart metadata and repository information
home: https://gnupg.org/
sources:
  - https://github.com/vladgh/docker_base_images
  - https://gnupg.org/download/
icon: https://gnupg.org/share/logo-gnupg-light-purple-bg.png

# Chart categorization and discovery
keywords:
  - gpg
  - gnupg
  - cryptography
  - encryption
  - key-management
  - digital-signatures
  - security
  - secrets-management
  - kubernetes
  - sas-ram

# Maintainer information
maintainers:
  - name: SAS Institute
    email: support@sas.com
    url: https://www.sas.com
  - name: Vladimir Ghetau
    email: vladimir@ghetau.org
    url: https://github.com/vladgh

# Enhanced Artifact Hub annotations
annotations:
  # Licensing and legal information
  artifacthub.io/license: "GPL-3.0"
  artifacthub.io/operator: "false"
  artifacthub.io/prerelease: "false"
  
  # Chart documentation and links
  artifacthub.io/links: |
    - name: GnuPG Documentation
      url: https://gnupg.org/documentation/
    - name: GPG Command Reference
      url: https://gnupg.org/gph/en/manual.html
    - name: Source Repository
      url: https://github.com/vladgh/docker_base_images
  
  # Container images used by this chart
  artifacthub.io/images: |
    - name: gpg
      image: vladgh/gpg:1.3.6
      whitelisted: true
    - name: gpg-alpine
      image: vladgh/gpg:1.3.6-alpine
      whitelisted: true
  
  # Deployment and operational information
  artifacthub.io/recommendations: |
    - url: https://artifacthub.io/packages/helm/kubernetes/kubernetes-secret-generator
      title: Kubernetes Secret Generator
    - url: https://artifacthub.io/packages/helm/external-secrets/external-secrets
      title: External Secrets Operator
    - url: https://artifacthub.io/packages/helm/cert-manager/cert-manager
      title: Cert-Manager for Certificate Management
  
  # Deployment requirements and dependencies
  artifacthub.io/dependencies: |
    - name: kubernetes
      version: ">=1.20.0"
      condition: required
    - name: rbac
      version: ">=1.0.0"
      condition: security.rbac.enabled
  
  # Resource allocation recommendations
  resources.cpu.min: "50m"
  resources.cpu.max: "500m"
  resources.memory.min: "64Mi"
  resources.memory.max: "256Mi"
  
  # Security and cryptographic requirements
  security.capabilities.required: "true"
  security.context.runAsNonRoot: "true"
  security.context.readOnlyRootFilesystem: "true"
  cryptography.keyLength.min: "2048"
  cryptography.keyLength.recommended: "4096"
  
  # Job and operational patterns
  job.completions: "1"
  job.parallelism: "1"
  job.backoffLimit: "3"
  job.activeDeadlineSeconds: "300"
  
  # Compatibility and version information
  kubernetes.version.min: "1.20.0"
  kubernetes.version.max: "1.30.0"
  helm.version.min: "3.8.0"
  
  # Chart category and classification
  category: "Security"
  subcategory: "Cryptography"
  use-case: "Key Management"