---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "keycloak.oauthProxy.fullname" . | lower }}
  labels:
    {{- include "keycloak.oauthProxy.labels" . | nindent 4 }}
type: Opaque
stringData:
    cookie-secret: {{ include "keycloak.oauthProxy.cookieSecret" . }}