{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "keycloak.oauthProxy.serviceAccountName" . }}
  labels:
    {{- include "keycloak.oauthProxy.labels" . | nindent 4 }}
  {{- with .Values.oauthProxy.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.oauthProxy.serviceAccount.automount }}
{{- end }}