apiVersion: v2
name: sas-retrieval-agent-manager-db-init
description: A Helm chart for SAS Retrieval Agent Manager Database Initialization - PostgreSQL database setup and schema creation for AI/ML workloads
type: application
version: 1.1.0
appVersion: "1.16.0"

# Chart metadata and repository information
home: https://www.sas.com/
sources:
  - https://github.com/sas-institute-rnd-internal/tmp-viya-iot-ram-helm
  - https://www.postgresql.org/
icon: https://www.sas.com/content/dam/SAS/sasbrand/Images/Logos/sas-logo-midnight.png

# Chart categorization and discovery
keywords:
  - sas
  - retrieval-agent-manager
  - database
  - initialization
  - postgresql
  - schema-creation
  - database-setup
  - migration
  - sql
  - data-initialization
  - bootstrap
  - setup-job
  - database-migration
  - ai-database
  - vector-database
  - kubernetes
  - init-container

# Maintainer information
maintainers:
  - name: SAS Institute
    email: support@sas.com
    url: https://www.sas.com
  - name: SAS IoT Team
    email: iot-support@sas.com
    url: https://www.sas.com/en_us/software/iot.html

# Enhanced Artifact Hub annotations
annotations:
  # Licensing and legal information
  artifacthub.io/license: "SAS Proprietary"
  artifacthub.io/operator: "false"
  artifacthub.io/prerelease: "false"
  
  # Chart documentation and links
  artifacthub.io/links: |
    - name: PostgreSQL Documentation
      url: https://www.postgresql.org/docs/
    - name: PostgreSQL Administration
      url: https://www.postgresql.org/docs/current/admin.html
    - name: SAS Viya Platform
      url: https://www.sas.com/en_us/software/viya.html
    - name: Database Migration Best Practices
      url: https://www.postgresql.org/docs/current/backup-dump.html
    - name: SAS Container Registry
      url: https://cr.sas.com/
  
  # Container images used by this chart
  artifacthub.io/images: |
    - name: postgresql
      image: postgres:15-alpine
      whitelisted: true
    - name: postgresql
      image: postgres:15-alpine
      whitelisted: true
    - name: k8s
      image: alpine/k8s:1.31.12
      whitelisted: true
  
  # Resource allocation recommendations for database jobs
  resources.cpu.min: "100m"
  resources.cpu.max: "2"
  resources.memory.min: "256Mi"
  resources.memory.max: "2Gi"
  
  # Database initialization capabilities
  database.type: "postgresql"
  database.version.min: "12.0"
  database.version.recommended: "15.0"
  database.extensions.supported: "true"
  database.schemas.creation: "true"
  database.users.creation: "true"
  database.roles.creation: "true"
  
  # AI/ML database features
  ai.vector.extensions: "pgvector"
  ai.embedding.support: "true"
  ai.similarity.search: "true"
  ai.indexing.vector: "true"
  ml.data.preparation: "true"
  
  # Security and authentication for database
  security.ssl.required: "true"
  security.encryption.at-rest: "true"
  security.rbac.database: "true"
  security.password.policy: "strict"
  authentication.methods: "md5,scram-sha-256"
  
  # Migration and backup capabilities
  migration.schema.supported: "true"
  migration.data.supported: "true"
  migration.rollback.supported: "true"
  backup.dump.supported: "true"
  backup.incremental.supported: "true"
  
  # Job execution patterns
  job.type: "initialization"
  job.completion.mode: "once"
  job.retry.policy: "OnFailure"
  job.backoff.limit: "5"
  job.deadline.seconds: "1800"
  job.restart.policy: "Never"
  
  # Initialization capabilities
  init.database.creation: "true"
  init.schema.creation: "true"
  init.user.creation: "true"
  init.role.creation: "true"
  init.extension.installation: "true"
  init.data.seeding: "true"
  
  # Performance and optimization
  performance.connection.pooling: "supported"
  performance.indexing.optimization: "true"
  performance.query.optimization: "true"
  performance.vacuum.automation: "true"
  
  # Monitoring and observability
  monitoring.job.status: "true"
  monitoring.database.health: "true"
  monitoring.connection.metrics: "true"
  logging.initialization.detailed: "true"
  observability.job.tracing: "true"
  
  # Configuration management
  config.environment.variables: "true"
  config.secrets.management: "true"
  config.configmap.support: "true"
  config.volume.mounts: "true"
  
  # High availability and reliability
  reliability.idempotent: "true"
  reliability.atomic.operations: "true"
  reliability.transaction.safety: "true"
  ha.multi.master: "supported"
  ha.read.replicas: "supported"
  
  # Compliance and governance
  compliance.data.governance: "true"
  compliance.audit.logging: "true"
  compliance.retention.policies: "true"
  governance.schema.versioning: "true"
  
  # Compatibility and version information
  kubernetes.version.min: "1.20.0"
  kubernetes.version.max: "1.30.0"
  helm.version.min: "3.8.0"
  
  # Chart category and classification
  category: "Database"
  subcategory: "Initialization"
  use-case: "Database Setup and Migration"