{{- if .Values.integrations.kueue.enabled }}
apiVersion: kueue.x-k8s.io/v1beta1
kind: ResourceFlavor
metadata:
  name: retrieval-agent-manager
  labels:
    {{- include "retrieval-agent-manager.labels" . | nindent 4 }}
{{- end }}