
{{ if .Values.ingress.domain }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-config" (include "keycloak.fullname" .) }}
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
data:
  namespace: {{ .Release.Namespace }}
  service: {{ include "keycloak.fullname" . }}
  host: "{{ .Values.ingress.domain }}"
  basePath: "{{ first .Values.ingress.keycloak.paths }}"
  url: "https://{{ .Values.ingress.domain }}{{ first .Values.ingress.keycloak.paths }}"
{{- end }}
