apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "keycloak.fullname" . }}
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
spec:
  {{- if not .Values.iam.keycloak.autoscaling.enabled }}
  replicas: {{ .Values.iam.keycloak.replicaCount }}
  {{- end }}
  {{- with .Values.iam.keycloak.strategy }}
  strategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "keycloak.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.iam.keycloak.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "keycloak.labels" . | nindent 8 }}
        {{- with .Values.iam.keycloak.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.images.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 12 }}
      {{- end }}
      serviceAccountName: {{ include "keycloak.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.iam.keycloak.podSecurityContext | nindent 8 }}
      initContainers:
        - name: check-db-ready
          image: "{{- include "images.postgres" . -}}"
          imagePullPolicy: IfNotPresent
          command: [
            'sh','-c', 
            '/scripts/init.sh'
          ]
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ printf "%s-keycloak-db-credentials" (include "retrieval-agent-manager.fullname" .) }}
                  key: user
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ printf "%s-keycloak-db-credentials" (include "retrieval-agent-manager.fullname" .) }}
                  key: password
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: {{ printf "%s-db-connection" (include "retrieval-agent-manager.fullname" .) }}
                  key: host
            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ printf "%s-db-connection" (include "retrieval-agent-manager.fullname" .) }}
                  key: port
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: {{ printf "%s-db-keycloak" (include "retrieval-agent-manager.fullname" .) }}
                  key: db
          resources:
            {{- toYaml .Values.iam.keycloak.resources | nindent 12 }}
          securityContext:
            {{- toYaml .Values.iam.keycloak.securityContext | nindent 12 }}
          volumeMounts:
            - mountPath: /scripts
              name: kc-scripts
              readOnly: false
        - name: copy-keycloak-theme
          image: "{{- include "images.theme" . -}}"
          imagePullPolicy: IfNotPresent
          command: ['sh', '-c', 
             'cp /opt/sas/viya/home/sas-iot-keycloak-theme-*.jar /opt/keycloak/providers']
          volumeMounts:
            - mountPath: /opt/keycloak/providers
              name: providers
              readOnly: false
          securityContext:
            {{- toYaml .Values.iam.keycloak.securityContext | nindent 12 }}
          resources:
            {{- toYaml .Values.iam.keycloak.resources | nindent 12 }}
        - name: keycloak-build
          image: "{{- include "images.keycloak" . -}}"
          imagePullPolicy: {{ .Values.images.keycloak.pullPolicy }}
          env:
            - name: KC_NS
              value: "{{ .Release.Namespace }}"
            - name: KC_DB
              value: postgres
            - name: KC_HOSTNAME
              valueFrom:
                configMapKeyRef:
                  key: url
                  name: {{ printf "%s-config" (include "keycloak.fullname" .) }}
            - name: KC_HOSTNAME_STRICT
              value: {{ .Values.iam.keycloak.config.strictHostname | quote }}
            - name: KC_HTTP_RELATIVE_PATH
              valueFrom:
                configMapKeyRef:
                  key: basePath
                  name: {{ printf "%s-config" (include "keycloak.fullname" .) }}
            - name: KC_PROXY_HEADERS
              value: xforwarded
            - name: KC_HTTP_ENABLED
              value: 'true'
            - name: KC_THEME_NAME
              value: {{ .Values.iam.keycloak.config.theme }}
            - name: KC_REALM_CLIENT_SERVICEACCOUNTSENABLED
              value: {{ .Values.iam.keycloak.config.serviceaccountsEnabled | quote }}
            - name: KC_REALM_NAME
              valueFrom:
                secretKeyRef:
                  name: {{ printf "%s-client-secret" (include "keycloak.fullname" .) }}
                  key: realm
            - name: KC_OAUTH2_ADMIN_ROLE
              valueFrom:
                configMapKeyRef:
                  key: adminRole
                  name: {{ printf "%s-app-roles" (include "retrieval-agent-manager.fullname" .) }}
            - name: KC_OAUTH2_USER_ROLE
              valueFrom:
                configMapKeyRef:
                  key: userRole
                  name: {{ printf "%s-app-roles" (include "retrieval-agent-manager.fullname" .) }}
            - name: KC_HEALTH_ENABLED
              value: "true"
            - name: KC_HTTPS_CERTIFICATE_FILE
              value: "/tls/tls.crt"
            - name: KC_HTTPS_CERTIFICATE_KEY_FILE
              value: "/tls/tls.key"
            - name: KC_HTTP_MANAGEMENT_RELATIVE_PATH
              value: "/"
            - name: KC_HTTP_MANAGEMENT_HEALTH_ENABLED
              value: "true"
            - name: KC_HEALTH_ENABLED
              value: "true"
            - name: KC_METRICS_ENABLED
              value: "true"
          command: ["/bin/bash", "-c"]
          args:
            - |
              cp -rf /opt/keycloak/* /keycloak/ &&
              cd /keycloak &&
              ls -laR &&
              ./bin/kc.sh build --features=token-exchange
          resources:
            {{- toYaml .Values.iam.keycloak.resources | nindent 12 }}
          securityContext:
            {{- toYaml .Values.iam.keycloak.securityContext | nindent 12 }}
          volumeMounts:
            - mountPath: /opt/keycloak/providers
              name: providers
              readOnly: true
            - name: keycloak
              mountPath: /keycloak
              readOnly: false
            - name: realm-config
              mountPath: /opt/keycloak/data/import/realm-export.json
              subPath: realm-export.json
              readOnly: false
      containers:
        - name: keycloak-run
          securityContext:
            {{- toYaml .Values.iam.keycloak.securityContext | nindent 12 }}
          image: "{{- include "images.keycloak" . -}}"
          imagePullPolicy: {{ .Values.images.keycloak.pullPolicy }}
          args:
            - start
            - --import-realm
            - --optimized
            # - --features=token-exchange
            - --verbose
          env:
            - name: KC_NS
              value: "{{ .Release.Namespace }}"
            - name: KC_DB
              value: postgres
            - name: KC_FQDN
              valueFrom:
                configMapKeyRef:
                  key: host
                  name: {{ printf "%s-config" (include "keycloak.fullname" .) }}
            - name: KC_DB_URL_HOST
              valueFrom:
                configMapKeyRef:
                  key: host
                  name: {{ printf "%s-db-connection" (include "retrieval-agent-manager.fullname" .) }}
            - name: KC_DB_URL_PORT
              valueFrom:
                configMapKeyRef:
                  key: port
                  name: {{ printf "%s-db-connection" (include "retrieval-agent-manager.fullname" .) }}
            - name: KC_DB_URL_DATABASE
              valueFrom:
                configMapKeyRef:
                  key: db
                  name: {{ printf "%s-db-keycloak" (include "retrieval-agent-manager.fullname" .) }}
            - name: KC_DB_SCHEMA
              valueFrom:
                configMapKeyRef:
                  key: schema
                  name: {{ printf "%s-db-keycloak" (include "retrieval-agent-manager.fullname" .) }}
            - name: KC_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ printf "%s-keycloak-db-credentials" (include "retrieval-agent-manager.fullname" .) }}
                  key: user
            - name: KC_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ printf "%s-keycloak-db-credentials" (include "retrieval-agent-manager.fullname" .) }}
                  key: password
            - name: KC_HOSTNAME
              valueFrom:
                configMapKeyRef:
                  key: url
                  name: {{ printf "%s-config" (include "keycloak.fullname" .) }}
            - name: KC_HOSTNAME_STRICT
              value: {{ .Values.iam.keycloak.config.strictHostname | quote }}
            - name: KC_HTTP_RELATIVE_PATH
              valueFrom:
                configMapKeyRef:
                  key: basePath
                  name: {{ printf "%s-config" (include "keycloak.fullname" .) }}
            - name: KC_PROXY_HEADERS
              value: xforwarded
            - name: KC_HTTP_ENABLED
              value: 'true'
            - name: KC_HTTP_MANAGEMENT_RELATIVE_PATH
              value: "/"
            - name: KC_THEME_NAME
              value: {{ .Values.iam.keycloak.config.theme }}
            - name: KC_REALM_CLIENT_SERVICEACCOUNTSENABLED
              value: {{ .Values.iam.keycloak.config.serviceaccountsEnabled | quote }}
            - name: KC_BOOTSTRAP_ADMIN_USERNAME
              valueFrom:
                secretKeyRef:
                  key: user
                  name: {{ printf "%s-admin-secret" (include "keycloak.fullname" .) }}
            - name: KC_BOOTSTRAP_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: {{ printf "%s-admin-secret" (include "keycloak.fullname" .) }}
            - name: APP_ADMIN
              valueFrom:
                secretKeyRef:
                  key: user
                  name: {{ printf "%s-appadmin-secret" (include "keycloak.fullname" .) }}
            - name: APP_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: {{ printf "%s-appadmin-secret" (include "keycloak.fullname" .) }}
            - name: OAUTH2_PROXY_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: {{ printf "%s-client-secret" (include "keycloak.fullname" .) }}
                  key: sv-client-id
            - name: OAUTH2_PROXY_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ printf "%s-client-secret" (include "keycloak.fullname" .) }}
                  key: sv-client-secret
            - name: KC_REALM_NAME
              valueFrom:
                secretKeyRef:
                  name: {{ printf "%s-client-secret" (include "keycloak.fullname" .) }}
                  key: realm
            - name: KC_OAUTH2_ADMIN_ROLE
              valueFrom:
                configMapKeyRef:
                  key: adminRole
                  name: {{ printf "%s-app-roles" (include "retrieval-agent-manager.fullname" .) }}
            - name: KC_OAUTH2_USER_ROLE
              valueFrom:
                configMapKeyRef:
                  key: userRole
                  name: {{ printf "%s-app-roles" (include "retrieval-agent-manager.fullname" .) }}
            - name: KC_HEALTH_ENABLED
              value: "true"
            - name: KC_HTTPS_CERTIFICATE_FILE
              value: "/tls/tls.crt"
            - name: KC_HTTPS_CERTIFICATE_KEY_FILE
              value: "/tls/tls.key"
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: KC_CACHE_EMBEDDED_NETWORK_BIND_ADDRESS
              value: '$(POD_IP)'
            - name: KC_HTTP_MANAGEMENT_HEALTH_ENABLED
              value: "true"
            - name: KC_HEALTH_ENABLED
              value: "true"
            - name: KC_METRICS_ENABLED
              value: "true"
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
            - containerPort: 9000
              name: management
              protocol: TCP
          startupProbe:
            {{- include "keycloak.startupProbe" . | nindent 12 }}
          livenessProbe:
            {{- include "keycloak.livenessProbe" . | nindent 12 }}
          readinessProbe:
            {{- include "keycloak.readinessProbe" . | nindent 12 }}
          resources:
            {{- toYaml .Values.iam.keycloak.resources | nindent 12 }}
          volumeMounts:
            - name: cache
              mountPath: /opt/keycloak/.cache
              readOnly: false
            - mountPath: /opt/keycloak
              name: keycloak
            - mountPath: /opt/keycloak/data/import
              name: realm-config
              readOnly: true
            {{- if .Values.ingress.tls.secretName }}
            - mountPath: /tls/
              name: ingress-tls
              readOnly: true
            {{- end }}
            - mountPath: /tmp
              name: tmp
            {{- if .Values.integrations.trustedCerts.enabled }}
            - mountPath: /opt/keycloak/conf/truststores
              name: trusted-certs-volume
              readOnly: true
            {{- end }}
          {{- with .Values.iam.keycloak.volumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: realm-config
          secret:
            defaultMode: 0444
            secretName: {{ printf "%s-realm-secret" (include "keycloak.fullname" .) }}
        - name: kc-scripts
          configMap:
            name: {{ include "keycloak.fullname" . }}-scripts
            defaultMode: 0755
        {{- if .Values.ingress.tls.secretName }}
        - name: ingress-tls
          secret:
            secretName: {{ .Values.ingress.tls.secretName }}
        {{- end }}
        - name: providers
          emptyDir:
            sizeLimit: 256Mi
        - name: keycloak
          emptyDir:
            sizeLimit: 256Mi
        - name: cache
          emptyDir:
            sizeLimit: 256Mi
        - name: tmp
          emptyDir:
            sizeLimit: 256Mi
        {{- if .Values.integrations.trustedCerts.enabled }}
        - name: trusted-certs-volume
          {{- if eq (.Values.integrations.trustedCerts.type | lower) "configmap" }}
          configMap:
            name: {{ .Values.integrations.trustedCerts.name }}
            optional: true
          {{- else if eq (.Values.integrations.trustedCerts.type | lower) "secret" }}
          secret:
            secretName: {{ .Values.integrations.trustedCerts.name }}
            optional: true
          {{- end }}
        {{- end }}
      {{- with .Values.iam.keycloak.volumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.iam.keycloak.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.iam.keycloak.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.iam.keycloak.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
