---
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-appadmin-secret" (include "keycloak.fullname" .) }}
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
type: Opaque
stringData:
  user: {{ .Values.users.application.admin.username }}
  password: {{ .Values.users.application.admin.password | quote }}
