---
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-admin-secret" (include "keycloak.fullname" .) }}
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
type: Opaque
stringData:
  user: {{ .Values.users.keycloak.admin.username | quote }}
  password: {{ .Values.users.keycloak.admin.password | quote }}
