{{ if .Values.ingress.domain }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-client-secret" (include "keycloak.fullname" .) }}
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
type: Opaque
stringData:
  url: "http://{{ include "keycloak.fullname" . }}:{{ .Values.iam.keycloak.service.port }}"
  oauthUrl: "https://{{ .Values.ingress.domain }}{{ first .Values.ingress.oauthProxy.paths }}"
  realm: {{ .Values.iam.keycloak.config.realm | quote }}
  sv-client-id: {{ .Values.iam.keycloak.config.clientId | quote }}
  sv-client-secret: {{ include "keycloak.clientSecret" . | quote }}
{{- end }}
