apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "postgrest.fullname" . }}-scripts
  labels:
    {{- include "postgrest.labels" . | nindent 4 }}
data:
  wait_for_postgres.sh: |-
    #/bin/sh
    PSQL=`which psql`

    until pg_isready -h $DB_HOST -p $DB_PORT -U $DB_USER; 
    do
      echo "Waiting for database to be ready ...";
      sleep 2;
    done;
    echo "The database is ready";

  wait_for_secret.sh: |-
    #/bin/sh

    KUBECTL=`which kubectl`
    cd /workdir

    while true; do
      if ${KUBECTL} get secret -n {{ .Release.Namespace }} keycloak-certs; then
        echo "Secret found!"
        break
      fi
      echo "Waiting for secret..."
      sleep 5
    done

  # postgrest_entrypoint.sh: |-
  #   #/bin/sh

  #   export PGRST_DB_URI="postgresql://${DB_USER}:${PGPASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}"

  #   # Start PostgREST
  #   exec postgrest /postgrest-config/postgrest.conf
