apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.storage.application.pvc.name }}
  labels:
    {{- include "storage.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
spec:
  accessModes:
    {{- range .Values.storage.application.pvc.accessModes }}
    - {{ . | quote }}
    {{- end }}
  resources:
    requests:
      storage: {{ .Values.storage.application.pvc.size | quote }}
  storageClassName: {{ default (include "retrieval-agent-manager.defaultStorageClassName" .) .Values.storage.application.pvc.storageClassName }}
