{{- if not .Values.storage.embedding.pvc.existingClaim }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: embedding-pv
  labels:
    {{- include "storage.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
spec:
  accessModes:
    {{- range .Values.storage.embedding.pvc.accessModes }}
    - {{ . | quote }}
    {{- end }}
  resources:
    requests:
      storage: {{ .Values.storage.embedding.pvc.size | quote }}
  storageClassName: {{ default (include "retrieval-agent-manager.defaultStorageClassName" .) .Values.storage.embedding.pvc.storageClassName }}
{{- end }}
