#######################################################################################
##### NOTICE: YOU MUST CHANGE ANY FIELD ECLOSED WITH <>                           #####
##### For a more detailed explanation, see the Values.yaml in the helm directory. #####
#######################################################################################

# -- Ingress TLS secret for RAM HTTPS termination
# -- TLS Certificate for secure access
extraObjects:
  - apiVersion: v1
    kind: Secret
    metadata:
      name: ingress-tls
    data:
      tls.crt:
        <base64-encoded TLS certificate>
      tls.key:
        <base64-encoded TLS private key>
    type: kubernetes.io/tls

# -- Changes deployment to use Routes and SecurityContextConstraints for OpenShift
platform: "openshift"

# -- Pull secret for SAS Registry that was created earlier in the deployment guide
images:
  imagePullSecrets:
    - name: cr-sas-secret

# -- User configuration for RAM components, including database credentials, Keycloak credentials, and application users
users:
  application:
    admin:
      username: <your_application_username_here>
      # Password requirements: Minimum 8 characters, at least one uppercase letter, one lowercase letter, one number and one special character
      password: <your_secure_password_here>
  monitoring:
    username: ocp_mon_pgrest_user
    password: <your_secure_password_here>
  keycloak:
    admin:
      username: <your_keycloak_username_here>
      # Password requirements: Minimum 8 characters, at least one uppercase letter, one lowercase letter, one number and one special character
      password: <your_secure_password_here>
    user:
      username: ocp_keycloak_user
      password: <your_secure_password_here>
  database:
    admin:
      username: <your_psql_admin_username_here>
      password: <your_psql_admin_password_here>
  embedding:
    username: ocp_embedding_user
    password: <your_secure_password_here>
  postgrest:
    username: ocp_pgrest_user
    password: <your_secure_password_here>
  migration:
    username: ocp_migration_user
    password: <your_secure_password_here>
  otel:
    username: ocp_otel_user
    password: <your_secure_password_here>
  vectorizationJob:
    username: ocp_vectorization_user
    password: <your_secure_password_here>
  vectorStore:
    username: ocp_vector_store_user
    password: <your_secure_password_here>

# -- Ingress configuration for RAM, including domain and TLS settings
ingress:
  domain: <your_ingress_domain_here>
  tls:
    secretName: ingress-tls

# -- API configuration, including license
api:
  config:
    license:
      <your_b64_encoded_license_here>

# -- Database configuration for RAM, including host, port, SSL mode, and credentials for application and monitoring database roles
db:
  init:
    config:
      database:
        host: <your_database_host_here>
        port: '5432'
        sslmode: require
      application:
        adminRole: ocp_ram_admin_role
        userRole: ocp_ram_user_role
      monitoring:
        adminRole: ocp_ram_admin_role
        userRole: ocp_ram_user_role

# -- Security configuration for RAM, including GPG passphrase for encrypting sensitive data such as database credentials and API license
security:
  gpg:
    config:
      # Example: passphrase: SomeVeryStrong1000CharPassPhraseThatIsNotUsedAnywhere
      passphrase: <your_secure_passphrase_here>

# -- IAM configuration for RAM, including Keycloak roles and credentials for admin and user database roles
iam:
  keycloak:
    config:
      adminRole: ocp_ram_admin_role
      userRole: ocp_ram_user_role
      # -- OAuth2 client secret
      # Example: plI1xWllgmSNnUZLprWkpSHldFhpWmBRVVnYW2YCcYZ
      clientSecret: <your_client_secret_here>
      # -- OAuth2 cookie secret
      # Example: ZNmYgcS1pWHkmpRYplUlBrdLVhnFIYVZWSW2lnlxWpC
      cookieSecret: <your_cookie_secret_here>
