apiVersion: v2
name: sas-retrieval-agent-manager-db-migration
description: A Helm chart for SAS Retrieval Agent Manager Database Migration - Schema migration with Goose for AI/ML database evolution
type: application
version: 1.1.0
appVersion: "1.16.0"

# Chart metadata and repository information
home: https://www.sas.com/
sources:
  - https://github.com/sas-institute-rnd-internal/tmp-viya-iot-ram-helm
  - https://github.com/pressly/goose
  - https://www.postgresql.org/
  - https://cr.sas.com/viya-4-x64_oci_linux_2-docker/sas-retrieval-agent-manager-db-migration
icon: https://www.sas.com/content/dam/SAS/sasbrand/Images/Logos/sas-logo-midnight.png

# Chart categorization and discovery
keywords:
  - sas
  - retrieval-agent-manager
  - database
  - migration
  - goose
  - schema-migration
  - database-evolution
  - versioning
  - postgresql
  - sql-migration
  - schema-versioning
  - database-upgrade
  - rollback
  - ai-database
  - vector-database
  - kubernetes
  - migration-job

# Maintainer information
maintainers:
  - name: SAS Institute
    email: support@sas.com
    url: https://www.sas.com
  - name: SAS IoT Team
    email: iot-support@sas.com
    url: https://www.sas.com/en_us/software/iot.html
  - name: Goose Project
    email: support@pressly.com
    url: https://github.com/pressly/goose

# Enhanced Artifact Hub annotations
annotations:
  # Licensing and legal information
  artifacthub.io/license: "SAS Proprietary"
  artifacthub.io/operator: "false"
  artifacthub.io/prerelease: "false"
  
  # Chart documentation and links
  artifacthub.io/links: |
    - name: Goose Migration Tool
      url: https://github.com/pressly/goose
    - name: Database Migration Best Practices
      url: https://github.com/pressly/goose#usage
    - name: PostgreSQL Documentation
      url: https://www.postgresql.org/docs/
    - name: Schema Migration Patterns
      url: https://martinfowler.com/articles/evodb.html
    - name: SAS Viya Platform
      url: https://www.sas.com/en_us/software/viya.html
  
  # Container images used by this chart
  artifacthub.io/images: |
    - name: sas-db-migration
      image: cr.sas.com/viya-4-x64_oci_linux_2-docker/sas-retrieval-agent-manager-db-migration:latest
      whitelisted: true
    - name: goose
      image: gomicro/goose:3.15.0
      whitelisted: true
    - name: postgres
      image: postgres:15-alpine
      whitelisted: true

  # Deployment requirements and dependencies
  artifacthub.io/dependencies: |
    - name: sas-retrieval-agent-manager-db-init
      version: ">=1.0.0"
      repository: local
      condition: initialization.required
  
  # Resource allocation recommendations for migration jobs
  resources.cpu.min: "100m"
  resources.cpu.max: "1"
  resources.memory.min: "256Mi"
  resources.memory.max: "1Gi"
  
  # Database migration capabilities
  migration.tool: "goose"
  migration.language: "sql"
  migration.versioning: "sequential"
  migration.rollback.supported: "true"
  migration.dry-run.supported: "true"
  migration.status.tracking: "true"
  
  # Database compatibility
  database.type: "postgresql"
  database.version.min: "12.0"
  database.version.recommended: "15.0"
  database.extensions.vector: "pgvector"
  database.extensions.ai: "true"
  
  # Migration execution patterns
  migration.strategy: "forward-only"
  migration.validation.pre: "true"
  migration.validation.post: "true"
  migration.atomic.transactions: "true"
  migration.checkpoint.support: "true"
  
  # Security and governance for migrations
  security.migration.review: "required"
  security.rollback.approval: "required"
  security.backup.pre-migration: "recommended"
  governance.change.tracking: "true"
  governance.approval.workflow: "true"
  
  # AI/ML specific migration features
  ai.vector.schema: "supported"
  ai.embedding.tables: "supported"
  ai.index.optimization: "true"
  ml.feature.tables: "supported"
  ml.model.metadata: "supported"
  
  # Job execution and reliability
  job.type: "migration"
  job.completion.mode: "sequential"
  job.retry.policy: "OnFailure"
  job.backoff.limit: "3"
  job.deadline.seconds: "3600"
  job.restart.policy: "Never"
  
  # Migration safety and validation
  safety.dry-run.default: "true"
  safety.backup.automatic: "recommended"
  safety.rollback.tested: "true"
  validation.syntax.check: "true"
  validation.dependency.check: "true"
  
  # Performance and optimization
  performance.migration.batching: "true"
  performance.index.concurrent: "true"
  performance.vacuum.post-migration: "true"
  performance.analyze.post-migration: "true"
  
  # Monitoring and observability
  monitoring.migration.progress: "true"
  monitoring.performance.metrics: "true"
  monitoring.error.detection: "true"
  logging.migration.detailed: "true"
  observability.migration.tracing: "true"
  
  # Version control and history
  versioning.schema.git: "integrated"
  versioning.migration.history: "tracked"
  versioning.rollback.history: "tracked"
  history.migration.audit: "comprehensive"
  
  # Environment and configuration
  config.environment.specific: "true"
  config.migration.path: "configurable"
  config.connection.pooling: "supported"
  config.timeout.configurable: "true"
  
  # High availability and disaster recovery
  ha.multi-environment: "supported"
  ha.zero-downtime: "strategies"
  dr.backup.integration: "true"
  dr.rollback.procedures: "documented"
  
  # Compliance and audit
  compliance.migration.audit: "full"
  compliance.change.approval: "workflow"
  compliance.rollback.approval: "required"
  audit.migration.log: "comprehensive"
  audit.user.tracking: "detailed"
  
  # Integration capabilities
  integration.ci-cd: "supported"
  integration.gitops: "compatible"
  integration.webhook.notifications: "true"
  integration.slack.alerts: "supported"
  
  # Compatibility and version information
  kubernetes.version.min: "1.20.0"
  kubernetes.version.max: "1.30.0"
  helm.version.min: "3.8.0"
  goose.version.min: "3.0.0"
  
  # Chart category and classification
  category: "Database"
  subcategory: "Migration"
  use-case: "Schema Evolution and Versioning"