apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-app-roles" (include "retrieval-agent-manager.fullname" .) }}
data:
  userRole: {{ .Values.db.init.config.application.userRole | quote }}
  adminRole: {{ .Values.db.init.config.application.adminRole | quote }}
