apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-application-db-credentials" (include "retrieval-agent-manager.fullname" .) }}
  labels:
    {{- include "db-initialization.labels" . | nindent 4 }}
stringData:
  user: {{ .Values.users.postgrest.username | quote }}
  password: {{ .Values.users.postgrest.password | quote }}
