apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-db-application" (include "retrieval-agent-manager.fullname" .) }}
  labels:
    {{- include "db-initialization.labels" . | nindent 4 }}
data:
  db: {{ .Values.db.init.config.application.db | quote }}
  schema: {{ .Values.db.init.config.application.schema | quote }}
