apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-admin-db-credentials" (include "retrieval-agent-manager.fullname" .) }}
  labels:
    {{- include "db-initialization.labels" . | nindent 4 }}
  annotations:
    # argocd.argoproj.io/sync-options: Skip
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    # helm.sh/hook: post-install
    # helm.sh/hook-delete-policy: before-hook-creation
stringData:
  user: {{ .Values.users.database.admin.username | quote }}
  password: {{ .Values.users.database.admin.password | quote }}
