apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-db-connection" (include "retrieval-agent-manager.fullname" .) }}
  labels:
    {{- include "db-initialization.labels" . | nindent 4 }}
data:
  host: {{ .Values.db.init.config.database.host | quote  }}
  port: {{ .Values.db.init.config.database.port | default "5432" | quote }}
  sslmode: {{ .Values.db.init.config.database.sslmode | toString }}
