apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-db-keycloak" (include "retrieval-agent-manager.fullname" .) }}
data:
  db: {{ .Values.db.init.config.keycloak.db | quote }}
  schema: {{ .Values.db.init.config.keycloak.schema | quote }}
