apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-db-monitoring" (include "retrieval-agent-manager.fullname" .) }}
  namespace: retagentmgr
  labels:
    {{- include "db-initialization.labels" . | nindent 4 }}
data:
  db: {{ .Values.db.init.config.monitoring.db | quote }}
  schema: {{ .Values.db.init.config.monitoring.schema | quote }}
