{{- if .Values.db.init.config.timescale.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-db-timescale" (include "retrieval-agent-manager.fullname" .) }}
  labels:
    {{- include "db-initialization.labels" . | nindent 4 }}
data:
  enabled: {{ .Values.db.init.config.timescale.enabled | quote }}
{{- end }}
