{{- if .Values.db.init.config.vectorStore.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-vector-store-db-credentials" (include "retrieval-agent-manager.fullname" .) }}
  labels:
    {{- include "db-initialization.labels" . | nindent 4 }}
stringData:
  user: {{ .Values.users.vectorStore.username | quote }}
  password: {{ .Values.users.vectorStore.password | quote }}
{{- end }}
