apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "db-initialization.fullname" . }}
  labels:
    {{- include "db-initialization.labels" . | nindent 4 }}
    ram-base-job: "true"
  annotations:
    argocd.argoproj.io/sync-options: Skip
    {{- with .Values.db.init.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  template:
    metadata:
      {{- with .Values.db.init.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "db-initialization.labels" . | nindent 8 }}
        {{- with .Values.db.init.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.images.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "db-initialization.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.db.init.podSecurityContext | nindent 8 }}
      initContainers:
        - name: initialization
          command:
            - "/bin/sh"
            - "-c"
            - "/scripts/initialize_database.sh"
          image: "{{- include "images.postgres" . -}}"
          imagePullPolicy: {{ .Values.images.postgres.pullPolicy }}
          securityContext:
            {{- toYaml .Values.db.init.securityContext | nindent 12 }}
          resources:
            {{- toYaml .Values.db.init.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /tmp
              name: temp-storage
            - name: db-connection
              mountPath: /config/db
            - name: db-admin-credentials
              mountPath: /secret/admin
              readOnly: true
            - name: db-embedding-credentials
              mountPath: /secret/embedding
              readOnly: true
            - name: db-keycloak-connection
              mountPath: /config/keycloak
            - name: db-keycloak-credentials
              mountPath: /secret/keycloak
              readOnly: true
            - name: db-migration-credentials
              mountPath: /secret/migration
              readOnly: true
            - name: db-application-connection
              mountPath: /config/postgrest
            - name: db-monitoring-connection
              mountPath: /config/monitoring
            - name: db-monitoring-credentials
              mountPath: /secret/monitoring
              readOnly: true
            - name: db-otel-credentials
              mountPath: /secret/otel
              readOnly: true
            - name: db-application-credentials
              mountPath: /secret/postgrest
              readOnly: true
            - name: db-vector-store-connection
              mountPath: /config/vectorstore
            - name: db-vector-store-credentials
              mountPath: /secret/vectorstore
              readOnly: true
            - name: db-vectorization-job-credentials
              mountPath: /secret/vectorizationjob
              readOnly: true
            - name: application-roles
              mountPath: /config/application-roles
            - name: monitoring-roles
              mountPath: /config/monitoring-roles
            - name: configmap-scripts
              mountPath: /scripts
      containers:
        - name: secret-cleaning
          command:
            - "/bin/sh"
            - "-c"
            - "/scripts/clean_admin_secret.sh"
          image: "{{- include "images.kubectl" . -}}"
          imagePullPolicy: {{ .Values.images.kubectl.pullPolicy }}
          securityContext:
            {{- toYaml .Values.db.init.securityContext | nindent 12 }}
          resources:
            {{- toYaml .Values.db.init.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /workdir
              name: workdir
            - mountPath: /tmp
              name: temp-storage
            - name: configmap-scripts
              mountPath: /scripts
      restartPolicy: OnFailure
      {{- with .Values.db.init.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.db.init.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.db.init.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: workdir
          emptyDir: {}
        - name: temp-storage
          emptyDir: {}
        - name: db-connection
          configMap:
            name: {{ printf "%s-db-connection" (include "retrieval-agent-manager.fullname" .) }}
        - name: db-admin-credentials
          secret:
            secretName: {{ printf "%s-admin-db-credentials" (include "retrieval-agent-manager.fullname" .) }}
        - name: db-embedding-credentials
          secret:
            secretName: {{ printf "%s-embedding-db-credentials" (include "retrieval-agent-manager.fullname" .) }}
        - name: db-keycloak-connection
          configMap:
            name: {{ printf "%s-db-keycloak" (include "retrieval-agent-manager.fullname" .) }}
        - name: db-keycloak-credentials
          secret:
            secretName: {{ printf "%s-keycloak-db-credentials" (include "retrieval-agent-manager.fullname" .) }}
        - name: db-migration-credentials
          secret:
            secretName: {{ printf "%s-migration-db-credentials" (include "retrieval-agent-manager.fullname" .) }}
        - name: db-application-connection
          configMap:
            name: {{ printf "%s-db-application" (include "retrieval-agent-manager.fullname" .) }}
        - name: db-monitoring-connection
          configMap:
            name: {{ printf "%s-db-monitoring" (include "retrieval-agent-manager.fullname" .) }}
        - name: db-monitoring-credentials
          secret:
            secretName: {{ printf "%s-monitoring-db-credentials" (include "retrieval-agent-manager.fullname" .) }}
        - name: db-otel-credentials
          secret:
            secretName: {{ printf "%s-otel-db-credentials" (include "retrieval-agent-manager.fullname" .) }}
        - name: db-application-credentials
          secret:
            secretName: {{ printf "%s-application-db-credentials" (include "retrieval-agent-manager.fullname" .) }}
        - name: db-vector-store-connection
          configMap:
            name: {{ printf "%s-db-vector-store" (include "retrieval-agent-manager.fullname" .) }}
        - name: db-vector-store-credentials
          secret:
            secretName: {{ printf "%s-vector-store-db-credentials" (include "retrieval-agent-manager.fullname" .) }}
        - name: db-vectorization-job-credentials
          secret:
            secretName: {{ printf "%s-vector-job-db-credentials" (include "retrieval-agent-manager.fullname" .) }}
        - name: application-roles
          configMap:
            name: {{ printf "%s-app-roles" (include "retrieval-agent-manager.fullname" .) }}
        - name: monitoring-roles
          configMap:
            name: {{ printf "%s-mon-roles" (include "retrieval-agent-manager.fullname" .) }}
        - name: configmap-scripts
          configMap:
            name: {{ include "db-initialization.fullname" . }}-scripts
            defaultMode: 0777
  backoffLimit: 1000
