apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tap
  # namespace: linkerd-viz
spec:
  secretName: tap-k8s-tls
  secretTemplate:
    labels:
      app.kubernetes.io/part-of: Linkerd
  duration: 168h    # 7 days duration.
  renewBefore: 24h  # Renew 1 day before expiration.
  issuerRef:
    name: linkerd-webhook-issuer
    kind: ClusterIssuer
  commonName: tap.linkerd-viz.svc
  dnsNames:
    - tap.linkerd-viz.svc
  isCA: false
  usages:
    - server auth