apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sas-retrieval-agent-manager-ui.fullname" . }}-configmap
  labels:
    {{- include "sas-retrieval-agent-manager-ui.labels" . | nindent 4 }}
data:
  nginx.conf: |-
    proxy_temp_path /tmp/proxy_temp;
    client_body_temp_path /tmp/client_temp;
    fastcgi_temp_path /tmp/fastcgi_temp;
    uwsgi_temp_path /tmp/uwsgi_temp;
    scgi_temp_path /tmp/scgi_temp;

    server {
        listen 8080;
        server_name  localhost;

        location = / {
            return 301 http://$host/SASRetrievalAgentManager/;
        }

        location = /SASRetrievalAgentManager/health/liveness {
            return 200;
        }

        location = /SASRetrievalAgentManager/health/readiness {
            return 200;
        }

        location ^~ /SASRetrievalAgentManager(/|$)(.*) {
            rewrite ^/SASRetrievalAgentManager(/|$)(.*)$ /SASRetrievalAgentManager/$2 last;
        }

        location = /SASRetrievalAgentManager {
            rewrite ^/SASRetrievalAgentManager$ /SASRetrievalAgentManager/ last;
        }

        location /SASRetrievalAgentManager/ {
            alias   /usr/share/nginx/html/;
            index  index.html index.htm;
            try_files $uri $uri/ /SASRetrievalAgentManager/index.html;
            client_max_body_size 100M;
        }

    }
