apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-scripts
  labels:
    {{- include "sas-retrieval-agent-manager-db-migration.labels" . | nindent 4 }}
data:
  wait_for_database.sh: |-
    #!/bin/bash
    PSQL=`which psql`

    export PGPASSWORD="$DB_PASSWORD"

    until pg_isready -h $DB_HOST -p $DB_PORT -U $DB_USER; 
    do
      echo "Waiting for database to be ready ...";
      sleep 2;
    done;
    echo "The database is ready";

    # Wait for the specific database to exist
    until $PSQL -h "$DB_HOST" -p "$DB_PORT" -U "$DB_USER" -d "$DB_NAME" -lqt | cut -d \| -f 1 | grep -qw "$DB_NAME"; do
      echo "Waiting for database '$DB_NAME' to be created..."
      sleep 2
    done

    echo "Database '$DB_NAME' is ready."

    # Wait for the specific schema to exist
    until $PSQL -h "$DB_HOST" -p "$DB_PORT" -U "$DB_USER" -d "$DB_NAME" -tAc "SELECT 1 FROM information_schema.schemata WHERE schema_name = '$DB_SCHEMA'" | grep -q 1; do
      echo "Waiting for schema '$DB_SCHEMA' to be present in database '$DB_NAME'..."
      sleep 2
    done

    echo "Schema '$DB_SCHEMA' is present."
